In [1]:
import pandas as pd
import numpy as np
import json
import re
from pathlib import Path

In [2]:
BASE_DIR = Path.home() / "Documents" / "datathon" / "track1_fintech_dataset_files"
PROJECT_DIR = BASE_DIR.parent
OUTPUT_DIR = PROJECT_DIR / "fraudlens_output"
print("Dataset folder:")
print(BASE_DIR)
print("Project folder:")
print(PROJECT_DIR)

Dataset folder:
/home/oai/Documents/datathon/track1_fintech_dataset_files
Project folder:
/home/oai/Documents/datathon

In [3]:
files = [
    "track1_upi_transactions.csv",
    "track1_kyc_records.csv",
    "track1_merchants_master.csv",
    "track1_chargebacks.json",
    "track1_dataset_notes.txt"
]

for file in files:
    path = BASE_DIR / file
    if path.exists():
        print(f"OK {file}")
    else:
        print(f"MISSING {file}")

OK track1_upi_transactions.csv
OK track1_kyc_records.csv
OK track1_merchants_master.csv
OK track1_chargebacks.json
OK track1_dataset_notes.txt

In [4]:
transactions = pd.read_csv(BASE_DIR / "track1_upi_transactions.csv")
kyc = pd.read_csv(BASE_DIR / "track1_kyc_records.csv")
merchants = pd.read_csv(BASE_DIR / "track1_merchants_master.csv")
with open(BASE_DIR / "track1_chargebacks.json", "r") as f:
    chargebacks = json.load(f)
chargebacks = pd.DataFrame(chargebacks)
print("All datasets loaded successfully!")

All datasets loaded successfully!

In [5]:
print("Transactions:", transactions.shape)
print("KYC:", kyc.shape)
print("Merchants:", merchants.shape)
print("Chargebacks:", chargebacks.shape)

Transactions: (20400, 8)
KYC: (36400, 12)
Merchants: (6210, 11)
Chargebacks: (2884, 13)

In [6]:
print("========== TRANSACTIONS ==========")
display(transactions.head())

print("\n========== KYC ==========")
display(kyc.head())

print("\n========== MERCHANTS ==========")
display(merchants.head())

print("\n========== CHARGEBACKS ==========")
display(chargebacks.head())

========== TRANSACTIONS ==========

        txn_id            timestamp  ...     mcc       status
0  TXN00011869  2026-01-15 00:11:30  ...  5411.0    COMPLETED
1  TXN00010383  2026-01-17 20:09:44  ...  4131.0   TXN_FAILED
2  TXN00008297  2026-01-23 14:10:16  ...  5411.0            S
3  TXN00006448           1770063471  ...  5411.0            S
4  TXN00018792  2026-03-31 14:02:37  ...  4131.0  TXN_SUCCESS

[5 rows x 8 columns]

========== KYC ==========

     user_id        full_name  ... kyc_status risk_segment
0   USR16112  Dhriti Deshmukh  ...       Done          LOW
1   USR17216       Megha Jani  ...   Verified       medium
2  USR 45454       PANINI LAL  ...    Pending         High
3   USR46189      Jack Parikh  ...   VERIFIED          low
4   USR85256         Eta Ravi  ...   APPROVED          LOW

[5 rows x 12 columns]

========== MERCHANTS ==========

  merchant_id  ... declared_avg_ticket_size
0     mch2849  ...             INR 2,432.18
1     MCH4314  ...                   986.05
2     MCH1986  ...             INR 1,427.52
3     mch3899  ...                 -1271.48
4     MCH4859  ...                  Rs. 214

[5 rows x 11 columns]

========== CHARGEBACKS ==========

  complaint_id       txn_id  ...  severity      channel
0   CBK0002082  TXN00004325  ...  Critical          ivr
1   CBK0001941  TXN00003720  ...         H  Call Center
2   CBK0001799  TXN00012539  ...        P4          IVR
3   CBK0002465  TXN00017802  ...         H          ivr
4   CBK0001870  TXN00015944  ...       Low          App

[5 rows x 13 columns]

In [7]:
def data_quality_report(df, name):
    report = pd.DataFrame({
        "column": df.columns,
        "dtype": df.dtypes.astype(str).values,
        "missing_count": df.isna().sum().values,
        "missing_%": (df.isna().mean() * 100).round(2).values,
        "unique_values": df.nunique(dropna=True).values
    })

    print(f"\n{'='*60}")
    print(f"{name.upper()} DATA QUALITY REPORT")
    print(f"{'='*60}")
    print(f"Rows: {len(df):,}")
    print(f"Columns: {len(df.columns)}")
    print(f"Duplicate rows: {df.duplicated().sum():,}")

    display(report)


data_quality_report(transactions, "Transactions")
data_quality_report(kyc, "KYC")
data_quality_report(merchants, "Merchants")
data_quality_report(chargebacks, "Chargebacks")

============================================================
TRANSACTIONS DATA QUALITY REPORT
============================================================
Rows: 20,400
Columns: 8
Duplicate rows: 400

        column    dtype  missing_count  missing_%  unique_values
0       txn_id   object              0       0.00          20000
1    timestamp   object              0       0.00          19083
2      user_id   object              0       0.00          17878
3  merchant_id   object              0       0.00           8051
4       amount   object              0       0.00          19900
5          utr   object           1024       5.02          19000
6          mcc  float64           2926      14.34              5
7       status   object              0       0.00             14

============================================================
KYC DATA QUALITY REPORT
============================================================
Rows: 36,400
Columns: 12
Duplicate rows: 278

              column   dtype  missing_count  missing_%  unique_values
0            user_id  object              0       0.00          32165
1          full_name  object              0       0.00          33921
2                pan  object           1896       5.21          33164
3            aadhaar  object           2664       7.32          32093
4      date_of_birth  object           2944       8.09          29284
5               city  object              0       0.00             41
6              state  object              0       0.00              9
7     monthly_income  object           2933       8.06          26034
8         occupation  object              0       0.00              9
9   signup_timestamp  object           2910       7.99          14607
10        kyc_status  object              0       0.00             16
11      risk_segment  object              0       0.00             12

============================================================
MERCHANTS DATA QUALITY REPORT
============================================================
Rows: 6,210
Columns: 11
Duplicate rows: 12

                      column   dtype  missing_count  missing_%  unique_values
0                merchant_id  object              0       0.00           5083
1              merchant_name  object              0       0.00           5732
2                        mcc  object            514       8.28             42
3          merchant_category  object              0       0.00             82
4              business_type  object              0       0.00             14
5                       city  object              0       0.00             41
6                      state  object              0       0.00              9
7            onboarding_date  object            499       8.04           4399
8         settlement_account  object           2451      39.47           3548
9            merchant_status  object              0       0.00             15
10  declared_avg_ticket_size  object            371       5.97           5520

============================================================
CHARGEBACKS DATA QUALITY REPORT
============================================================
Rows: 2,884
Columns: 13
Duplicate rows: 84

                     column   dtype  missing_count  missing_%  unique_values
0              complaint_id  object              0        0.0           2800
1                    txn_id  object              0        0.0           2582
2                   user_id  object              0        0.0           2454
3               merchant_id  object              0        0.0           2051
4     transaction_timestamp  object              0        0.0           1238
5        reported_timestamp  object              0        0.0           1329
6           disputed_amount  object              0        0.0           2609
7               reason_code  object              0        0.0             34
8            complaint_text  object              0        0.0             84
9         resolution_status  object              0        0.0             13
10  bank_response_timestamp  object              0        0.0           1149
11                 severity  object              0        0.0             16
12                  channel  object              0        0.0              8

In [8]:
display(transactions[["user_id"]].head(20))

     user_id
0   USR45826
1   USR79397
2   USR87810
3   USR54287
4   USR53865
5   USR90546
6   USR18691
7   USR16629
8   USR20899
9   USR51755
10  USR81003
11  USR70687
12  USR37834
13  USR78386
14  USR21114
15  USR96222
16  USR13976
17  USR55935
18  USR13890
19  USR15778

In [9]:
print(
    transactions["user_id"]
    .dropna()
    .astype(str)
    .str.contains(r"[-_ ]|^[a-z]", regex=True)
    .sum()
)

0

In [10]:
print("Transaction user IDs with formatting issues:",
      transactions["user_id"].dropna().astype(str)
      .str.contains(r"[-_ ]|^[a-z]", regex=True).sum())

print("KYC user IDs with formatting issues:",
      kyc["user_id"].dropna().astype(str)
      .str.contains(r"[-_ ]|^[a-z]", regex=True).sum())

print("Transaction merchant IDs with formatting issues:",
      transactions["merchant_id"].dropna().astype(str)
      .str.contains(r"[-_ ]|^[a-z]", regex=True).sum())

print("Merchant master IDs with formatting issues:",
      merchants["merchant_id"].dropna().astype(str)
      .str.contains(r"[-_ ]|^[a-z]", regex=True).sum())

Transaction user IDs with formatting issues: 0

KYC user IDs with formatting issues: 11416
Transaction merchant IDs with formatting issues: 0

Merchant master IDs with formatting issues: 1595

In [11]:
print("KYC examples:")
display(
    kyc.loc[
        kyc["user_id"].astype(str)
        .str.contains(r"[-_ ]|^[a-z]", regex=True),
        ["user_id"]
    ].head(20)
)

print("\nMerchant examples:")
display(
    merchants.loc[
        merchants["merchant_id"].astype(str)
        .str.contains(r"[-_ ]|^[a-z]", regex=True),
        ["merchant_id"]
    ].head(20)
)

KYC examples:

      user_id
2   USR 45454
5   USR 20918
6    usr22494
11  USR 65060
16  USR 77711
18  USR 53544
19   usr57699
21  USR 26959
27  USR 37121
28  usr_64308
34  usr_41268
38  USR 75086
39  USR-78743
44   usr33108
48  USR 86614
49  USR-23635
55  USR 59175
56  USR-64276
57  USR-64768
71  USR 78059

Merchant examples:

   merchant_id
0      mch2849
3      mch3899
7     MCH-2637
9     MCH 2430
11    MCH 9997
13    MCH 6945
14     mch4323
15     mch1405
18     mch9620
21     mch2934
24     mch2849
26    MCH 2749
29     mch9951
30     mch4962
32     mch3442
33    MCH 9993
35    MCH-2536
38    MCH 2665
40    MCH-4729
41     mch6326

In [12]:
def clean_user_id(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x)
    x = x.upper()
    x = x.replace(" ", "")
    x = x.replace("-", "")
    x = x.replace("_", "")
    
    return x

In [13]:
def clean_merchant_id(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x)
    x = x.upper()
    x = x.replace(" ", "")
    x = x.replace("-", "")
    x = x.replace("_", "")
    
    return x

In [14]:
kyc["user_id_clean"] = kyc["user_id"].apply(clean_user_id)

merchants["merchant_id_clean"] = merchants["merchant_id"].apply(clean_merchant_id)

transactions["user_id_clean"] = transactions["user_id"].apply(clean_user_id)

transactions["merchant_id_clean"] = transactions["merchant_id"].apply(clean_merchant_id)

In [15]:
def clean_txn_id(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x)
    x = x.upper()
    x = x.replace(" ", "")
    x = x.replace("-", "")
    x = x.replace("_", "")
    
    return x

In [16]:
transactions["txn_id_clean"] = transactions["txn_id"].apply(clean_txn_id)

chargebacks["txn_id_clean"] = chargebacks["txn_id"].apply(clean_txn_id)

In [17]:
print("========== TRANSACTIONS ==========")
display(transactions.head())

print("\n========== KYC ==========")
display(kyc.head())

print("\n========== MERCHANTS ==========")
display(merchants.head())

print("\n========== CHARGEBACKS ==========")
display(chargebacks.head())

========== TRANSACTIONS ==========

        txn_id            timestamp  ... merchant_id_clean txn_id_clean
0  TXN00011869  2026-01-15 00:11:30  ...           MCH7045  TXN00011869
1  TXN00010383  2026-01-17 20:09:44  ...           MCH5031  TXN00010383
2  TXN00008297  2026-01-23 14:10:16  ...           MCH9809  TXN00008297
3  TXN00006448           1770063471  ...           MCH6928  TXN00006448
4  TXN00018792  2026-03-31 14:02:37  ...           MCH8121  TXN00018792

[5 rows x 11 columns]

========== KYC ==========

     user_id        full_name         pan  ... kyc_status risk_segment user_id_clean
0   USR16112  Dhriti Deshmukh  SEJAA8194O  ...       Done          LOW      USR16112
1   USR17216       Megha Jani  QT0ZZ5561X  ...   Verified       medium      USR17216
2  USR 45454       PANINI LAL  QCNTL9489O  ...    Pending         High      USR45454
3   USR46189      Jack Parikh  RRVUI4059Q  ...   VERIFIED          low      USR46189
4   USR85256         Eta Ravi  ygvoi9236w  ...   APPROVED          LOW      USR85256

[5 rows x 13 columns]

========== MERCHANTS ==========

  merchant_id  ... merchant_id_clean
0     mch2849  ...           MCH2849
1     MCH4314  ...           MCH4314
2     MCH1986  ...           MCH1986
3     mch3899  ...           MCH3899
4     MCH4859  ...           MCH4859

[5 rows x 12 columns]

========== CHARGEBACKS ==========

  complaint_id       txn_id   user_id  ...  severity      channel txn_id_clean
0   CBK0002082  TXN00004325  usr97580  ...  Critical          ivr  TXN00004325
1   CBK0001941  TXN00003720  USR54113  ...         H  Call Center  TXN00003720
2   CBK0001799  TXN00012539  USR17980  ...        P4          IVR  TXN00012539
3   CBK0002465  TXN00017802  USR76148  ...         H          ivr  TXN00017802
4   CBK0001870  TXN00015944  USR24660  ...       Low          App  TXN00015944

[5 rows x 14 columns]

In [18]:
print("Duplicate KYC user IDs:", kyc["user_id_clean"].duplicated().sum())
print("Duplicate merchant IDs:", merchants["merchant_id_clean"].duplicated().sum())
print("Duplicate transaction IDs:", transactions["txn_id_clean"].duplicated().sum())

Duplicate KYC user IDs: 7045
Duplicate merchant IDs: 1730
Duplicate transaction IDs: 400

In [19]:
print("Duplicate KYC rows:", kyc.duplicated().sum())
print("Duplicate merchant rows:", merchants.duplicated().sum())
print("Duplicate transaction rows:", transactions.duplicated().sum())
print("Duplicate chargeback rows:", chargebacks.duplicated().sum())

Duplicate KYC rows: 278

Duplicate merchant rows: 12
Duplicate transaction rows: 400

Duplicate chargeback rows: 84

In [20]:
duplicate_users = kyc[
    kyc["user_id_clean"].duplicated(keep=False)
].sort_values("user_id_clean")

display(duplicate_users.head(30))

      user_id         full_name  ... risk_segment user_id_clean
13127   10098          xiti ben  ...          LOW         10098
949     10098          xiti ben  ...          LOW         10098
3873    11301    Baljiwan Singh  ...       medium         11301
27756   11301    Baljiwan Singh  ...       medium         11301
26409   11947    triya sachdeva  ...          Low         11947
21625   11947    Chatresh Mitra  ...       medium         11947
5451    12173       Ranbir Vasa  ...       Medium         12173
6254    12173       Ranbir Vasa  ...       Medium         12173
34833   16969      Michae1 Sant  ...          Low         16969
28573   16969      Michae1 Sant  ...          Low         16969
249     17255       Anusha Pant  ...          low         17255
32159   17255       Anusha Pant  ...          low         17255
11310   21292     Manbir Vaidya  ...          Low         21292
21351   21292     Manbir Vaidya  ...          Low         21292
15445   23776      Rachita Yogi  ...          Low         23776
12939   23776         Ojas Toor  ...          LOW         23776
16379   24005          Jai Deep  ...          LOW         24005
7885    24005          Jai Deep  ...          LOW         24005
3294    25377      DalajaButala  ...         high         25377
14353   25377      DalajaButala  ...         high         25377
4000    25446   Nicholas Barman  ...      Unknown         25446
20164   25446   Nicholas Barman  ...      Unknown         25446
28796   25581   Upadhriti Uppal  ...          Low         25581
15921   25581    Michae1 D0ct0r  ...          Low         25581
2605    26602        Krishna De  ...          low         26602
828     26602        Krishna De  ...          low         26602
13303   27892  Upadhriti Thaker  ...       medium         27892
21412   27892  Upadhriti Thaker  ...       medium         27892
14310   28288       ishwar wali  ...          Low         28288
34235   28288       ishwar wali  ...          Low         28288

[30 rows x 13 columns]

In [21]:
duplicate_merchants = merchants[
    merchants["merchant_id_clean"].duplicated(keep=False)
].sort_values("merchant_id_clean")

display(duplicate_merchants.head(30))

     merchant_id  ... merchant_id_clean
4172        1083  ...              1083
4188        1083  ...              1083
1088        1936  ...              1936
695         1936  ...              1936
1277        2274  ...              2274
2028        2274  ...              2274
4839        2885  ...              2885
2279        2885  ...              2885
2702        3023  ...              3023
227         3023  ...              3023
989         3875  ...              3875
944         3875  ...              3875
660         4583  ...              4583
3227        4583  ...              4583
804         5984  ...              5984
2480        5984  ...              5984
3995        7149  ...              7149
5438        7149  ...              7149
3048        8680  ...              8680
4135        8680  ...              8680
309         8756  ...              8756
5628        8756  ...              8756
465         9180  ...              9180
997         9180  ...              9180
1457        9546  ...              9546
431         9546  ...              9546
970      MCH1007  ...           MCH1007
3150     MCH1007  ...           MCH1007
2679     MCH1011  ...           MCH1011
1677     MCH1011  ...           MCH1011

[30 rows x 12 columns]

In [22]:
merchant_duplicate_summary = (
    merchants.groupby("merchant_id_clean")
    .agg(
        record_count=("merchant_id_clean", "size"),
        unique_names=("merchant_name", "nunique"),
        unique_categories=("merchant_category", "nunique"),
        unique_statuses=("merchant_status", "nunique")
    )
    .query("record_count > 1")
    .sort_values("record_count", ascending=False)
)

display(merchant_duplicate_summary.head(20))

                   record_count  ...  unique_statuses
merchant_id_clean                ...
MCH7600                       6  ...                3
MCH8125                       6  ...                6
MCH7912                       6  ...                5
MCH3659                       6  ...                5
MCH4322                       6  ...                4
MCH6061                       6  ...                3
MCH1816                       5  ...                4
MCH1101                       5  ...                4
MCH5683                       5  ...                4
MCH2981                       5  ...                2
MCH6743                       5  ...                4
MCH9393                       5  ...                3
MCH7724                       5  ...                2
MCH2384                       5  ...                5
MCH3612                       5  ...                3
MCH3837                       5  ...                2
MCH8297                       5  ...                5
MCH2418                       4  ...                4
MCH7430                       4  ...                4
MCH3189                       4  ...                3

[20 rows x 4 columns]

In [23]:
merchants["merchant_id_clean"].value_counts().value_counts().sort_index()

count
1    3162
2    1000
3     247
4      54
5      11
6       6
Name: count, dtype: int64

In [24]:
duplicate_transactions = transactions[
    transactions["txn_id_clean"].duplicated(keep=False)
].sort_values("txn_id_clean")

display(duplicate_transactions.head(20))

            txn_id            timestamp  ... merchant_id_clean txn_id_clean
15040  TXN00000013  2026-03-28 14:55:44  ...           MCH8391  TXN00000013
4370   TXN00000013  2026-03-28 14:55:44  ...           MCH8391  TXN00000013
5562   TXN00000057  2026-02-03 09:28:29  ...           MCH1149  TXN00000057
10826  TXN00000057  2026-02-03 09:28:29  ...           MCH1149  TXN00000057
10017  TXN00000071  2026-03-22 12:39:10  ...           MCH9536  TXN00000071
8513   TXN00000071  2026-03-22 12:39:10  ...           MCH9536  TXN00000071
222    TXN00000132  2026-01-31 15:03:31  ...           MCH5882  TXN00000132
18737  TXN00000132  2026-01-31 15:03:31  ...           MCH5882  TXN00000132
2701   TXN00000207           1767252823  ...           MCH2406  TXN00000207
16755  TXN00000207           1767252823  ...           MCH2406  TXN00000207
3872   TXN00000241  2026-02-05 05:48:23  ...           MCH8186  TXN00000241
928    TXN00000241  2026-02-05 05:48:23  ...           MCH8186  TXN00000241
3183   TXN00000271  2026-01-21 13:31:32  ...           MCH5897  TXN00000271
8121   TXN00000271  2026-01-21 13:31:32  ...           MCH5897  TXN00000271
1440   TXN00000343           1768051188  ...           MCH8208  TXN00000343
12905  TXN00000343           1768051188  ...           MCH8208  TXN00000343
11937  TXN00000356           1768401534  ...           MCH4444  TXN00000356
16257  TXN00000356           1768401534  ...           MCH4444  TXN00000356
6509   TXN00000412  06/01/2026 16:16:33  ...           MCH6062  TXN00000412
3499   TXN00000412  06/01/2026 16:16:33  ...           MCH6062  TXN00000412

[20 rows x 11 columns]

In [25]:
print("Rows before:", len(transactions))

transactions_clean = transactions.drop_duplicates().copy()

print("Rows after:", len(transactions_clean))

Rows before: 20400

Rows after: 20000

In [26]:
def clean_amount(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x)
   
    x = x.replace("₹", "")
    x = x.replace("INR", "")
    x = x.replace("Rs.", "")
    x = x.replace("Rs", "")
    
    
    x = x.replace(",", "")
    x = x.strip()
   
    return pd.to_numeric(x, errors="coerce")

In [27]:
transactions_clean["amount_clean"] = (
    transactions_clean["amount"].apply(clean_amount)
)

In [28]:
display(
    transactions_clean[["amount", "amount_clean"]].head(20)
)

          amount  amount_clean
0       15722.34      15722.34
1     Rs. 6362.9       6362.90
2       15446.19      15446.19
3       12110.49      12110.49
4   Rs. 19432.94      19432.94
5   Rs. 18866.03      18866.03
6       19982.69      19982.69
7    Rs. 22687.5      22687.50
8        8256.07       8256.07
9     ₹16,466.93      16466.93
10    INR 13,312      13312.00
11     17,833.99      17833.99
12  Rs. 19118.63      19118.63
13       2680.85       2680.85
14  Rs. 20100.92      20100.92
15      16257.95      16257.95
16        1575.7       1575.70
17      18230.29      18230.29
18     -23820.57     -23820.57
19     INR 5,546       5546.00

In [29]:
print("Missing/invalid cleaned amounts:",
      transactions_clean["amount_clean"].isna().sum())

print("Negative amounts:",
      (transactions_clean["amount_clean"] < 0).sum())

Missing/invalid cleaned amounts: 0
Negative amounts: 420

In [30]:
negative_transactions = transactions_clean[
    transactions_clean["amount_clean"] < 0
]

display(
    negative_transactions[
        ["txn_id", "timestamp", "user_id", "merchant_id",
         "amount", "amount_clean", "utr", "status"]
    ].head(20)
)

          txn_id               timestamp  ...             utr       status
18   TXN00011091     03/03/2026 19:17:39  ...   UTR6527062794    COMPLETED
110  TXN00004601  03-25-2026 07:19:26 AM  ...  UTR 7964275007    COMPLETED
174  TXN00015801     2026-01-18 16:30:53  ...  UTR 9996906622      Success
201  TXN00009208     2026-01-29 23:25:09  ...   UTR2481576524  TXN_SUCCESS
338  TXN00005676     2026-02-22 13:40:03  ...   UTR1673088613      SUCCESS
346  TXN00019598     2026-02-10 07:54:20  ...   UTR1611702612    COMPLETED
357  TXN00007985     2026-01-23 18:43:15  ...   UTR0505614019      SUCCESS
386  TXN00013599     2026-01-24 23:54:34  ...   UTR4458365104  TXN_SUCCESS
391  TXN00013687  03-11-2026 06:06:29 AM  ...   UTR6305064169  TXN_SUCCESS
413  TXN00018660     25/01/2026 06:21:41  ...   UTR9094931809  TXN_SUCCESS
438  TXN00010649     24/02/2026 05:22:08  ...   UTR1509546385            S
477  TXN00011572  02-04-2026 05:59:56 AM  ...   UTR5171097088    COMPLETED
485  TXN00012751     11/01/2026 02:40:06  ...   UTR1493969748  TXN_SUCCESS
549  TXN00016843     2026-01-11 05:21:43  ...   UTR7159833015      Success
701  TXN00012589     25/02/2026 06:52:08  ...   UTR2448935052   TXN_FAILED
705  TXN00002208              2026/03/10  ...   UTR3554843140  TXN_SUCCESS
749  TXN00014022     04/01/2026 17:12:07  ...   UTR3312059708            S
790  TXN00016827     27/03/2026 04:30:36  ...   UTR5846933534         Fail
819  TXN00002297     2026-03-03 07:14:02  ...   UTR1197214529      SUCCESS
838  TXN00001133     22/01/2026 12:21:25  ...   UTR2261910807    COMPLETED

[20 rows x 8 columns]

In [31]:
transactions_clean["negative_amount_flag"] = (
    transactions_clean["amount_clean"] < 0
).astype(int)

In [32]:
negative_status = (
    transactions_clean[
        transactions_clean["negative_amount_flag"] == 1
    ]["status"]
    .value_counts()
)

display(negative_status)

status
COMPLETED      75
Success        74
S              73
TXN_SUCCESS    69
SUCCESS        62
FAILED         12
TXN_FAILED     10
Fail            9
Declined        9
F               8
Initiated       7
PROCESSING      7
PENDING         3
Pending         2
Name: count, dtype: int64

In [33]:
def clean_status(x):
    if pd.isna(x):
        return "UNKNOWN"
    
    x = str(x).strip().upper()
    
    if x in ["SUCCESS", "S", "TXN_SUCCESS", "COMPLETED"]:
        return "SUCCESS"
    
    elif x in ["FAILED", "TXN_FAILED", "FAIL", "F", "DECLINED"]:
        return "FAILED"
    
    elif x in ["PENDING", "PROCESSING"]:
        return "PENDING"
    
    elif x == "INITIATED":
        return "INITIATED"
    
    else:
        return "UNKNOWN"

In [34]:
transactions_clean["status_clean"] = (
    transactions_clean["status"].apply(clean_status)
)

In [35]:
transactions_clean["status_clean"].value_counts()

status_clean
SUCCESS      17053
FAILED        1955
PENDING        772
INITIATED      220
Name: count, dtype: int64

In [36]:
transactions_clean["timestamp"].head(20)

0        2026-01-15 00:11:30
1        2026-01-17 20:09:44
2        2026-01-23 14:10:16
3                 1770063471
4        2026-03-31 14:02:37
5        2026-02-11 01:40:43
6     03-10-2026 09:27:31 PM
7        25/02/2026 00:53:02
8        2026-02-07 09:53:11
9     03-30-2026 09:37:49 AM
10       2026-03-14 12:21:17
11       2026-01-27 23:43:31
12       11/03/2026 01:40:12
13       2026-02-21 01:33:17
14       2026-02-21 05:47:48
15       21/01/2026 15:06:13
16       2026-03-06 13:48:49
17    01-09-2026 05:05:51 AM
18       03/03/2026 19:17:39
19       17/01/2026 18:53:31
Name: timestamp, dtype: object

In [37]:
transactions_clean["timestamp"].tail(20)

20377       11/02/2026 00:13:53
20378       2026-01-06 20:54:09
20379       2026-02-22 12:39:39
20381       2026-03-23 13:35:53
20382       2026-03-26 06:11:34
20383       15/03/2026 13:48:58
20384       2026-03-09 14:37:22
20386       19/01/2026 21:04:00
20387       2026-02-28 11:26:27
20388       2026-03-22 07:38:58
20389       2026-02-10 19:04:52
20390                2026/01/09
20391       2026-01-14 03:42:48
20392       23/01/2026 16:39:17
20394       2026-01-27 17:52:01
20395       12/01/2026 21:29:48
20396       20/01/2026 08:47:54
20397    02-11-2026 03:22:46 AM
20398       2026-01-20 19:27:07
20399       2026-02-28 00:01:26
Name: timestamp, dtype: object

In [38]:
def clean_timestamp(x):
    if pd.isna(x):
        return pd.NaT

    x = str(x).strip()

    # Unix timestamp
    if x.isdigit() and len(x) >= 9:
        return pd.to_datetime(
            int(x),
            unit="s",
            errors="coerce"
        )

    # Normal datetime formats
    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%m-%d-%Y %I:%M:%S %p",
        "%d/%m/%Y %H:%M:%S",
        "%d-%m-%Y %H:%M:%S",
        "%Y/%m/%d",
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            pass

    return pd.NaT

In [39]:
transactions_clean["timestamp_clean"] = (
    transactions_clean["timestamp"].apply(clean_timestamp)
)

In [40]:
transactions_clean["timestamp_clean"].isna().sum()

np.int64(0)

In [41]:
display(
    transactions_clean[
        transactions_clean["timestamp_clean"].isna()
    ][["timestamp"]].head(20)
)

Empty DataFrame
Columns: [timestamp]
Index: []

In [42]:
print(transactions_clean["timestamp_clean"].min())
print(transactions_clean["timestamp_clean"].max())
print(transactions_clean["timestamp_clean"].describe())

2026-01-01 00:00:00
2026-03-31 23:53:53
count                            20000
mean     2026-02-14 23:26:36.216049920
min                2026-01-01 00:00:00
25%      2026-01-23 14:02:29.249999872
50%                2026-02-15 00:14:18
75%         2026-03-09 05:47:17.500000
max                2026-03-31 23:53:53
Name: timestamp_clean, dtype: object

In [43]:
transactions_clean["utr"].head(20)

0      UTR6498104698
1      UTR7656190355
2      UTR9037001889
3      UTR5257823698
4      UTR4204272894
5      UTR2080442730
6      UTR5471158093
7      UTR3330570580
8      UTR6505850115
9     UTR 2787678319
10     UTR2464640119
11     UTR5315091377
12     UTR1692756805
13     UTR3430344329
14     UTR3572682179
15     UTR4021669116
16     UTR0496925866
17     UTR6094940155
18     UTR6527062794
19     UTR0928079796
Name: utr, dtype: object

In [44]:
def clean_utr(x):
    if pd.isna(x):
        return np.nan
    
    x = str(x).strip()
    x = x.upper()
    x = x.replace(" ", "")
    x = x.replace("-", "")
    x = x.replace("_", "")
    
    return x

In [45]:
transactions_clean["utr_clean"] = (
    transactions_clean["utr"].apply(clean_utr)
)

In [46]:
transactions_clean[["utr", "utr_clean"]].head(20)

               utr      utr_clean
0    UTR6498104698  UTR6498104698
1    UTR7656190355  UTR7656190355
2    UTR9037001889  UTR9037001889
3    UTR5257823698  UTR5257823698
4    UTR4204272894  UTR4204272894
5    UTR2080442730  UTR2080442730
6    UTR5471158093  UTR5471158093
7    UTR3330570580  UTR3330570580
8    UTR6505850115  UTR6505850115
9   UTR 2787678319  UTR2787678319
10   UTR2464640119  UTR2464640119
11   UTR5315091377  UTR5315091377
12   UTR1692756805  UTR1692756805
13   UTR3430344329  UTR3430344329
14   UTR3572682179  UTR3572682179
15   UTR4021669116  UTR4021669116
16   UTR0496925866  UTR0496925866
17   UTR6094940155  UTR6094940155
18   UTR6527062794  UTR6527062794
19   UTR0928079796  UTR0928079796

In [47]:
transactions_clean["missing_utr_flag"] = (
    transactions_clean["utr_clean"].isna()
).astype(int)

transactions_clean["missing_utr_flag"].value_counts()

missing_utr_flag
0    19000
1     1000
Name: count, dtype: int64

In [48]:
utr_pattern = r"^UTR\d{10}$"

transactions_clean["invalid_utr_flag"] = (
    transactions_clean["utr_clean"].notna()
    & ~transactions_clean["utr_clean"].str.match(utr_pattern, na=False)
).astype(int)

In [49]:
transactions_clean["invalid_utr_flag"].value_counts()

invalid_utr_flag
0    20000
Name: count, dtype: int64

In [50]:
display(
    transactions_clean[
        transactions_clean["invalid_utr_flag"] == 1
    ][["utr", "utr_clean"]].head(20)
)

Empty DataFrame
Columns: [utr, utr_clean]
Index: []

In [51]:
transactions_clean["mcc"].value_counts(dropna=False).head(30)

mcc
5411.0    5720
5912.0    2891
NaN       2872
5812.0    2866
7011.0    2827
4131.0    2824
Name: count, dtype: int64

In [52]:
transactions_clean["mcc"].nunique(dropna=True)

5

In [53]:
transactions_clean["mcc"].dropna().sample(30, random_state=42)

12525    7011.0
7077     5812.0
150      7011.0
5484     5912.0
5323     4131.0
15617    5411.0
12529    5411.0
4560     4131.0
17420    5912.0
7139     4131.0
6417     5411.0
10925    5411.0
11842    5812.0
12863    4131.0
7559     5812.0
19173    5411.0
15432    4131.0
1989     5812.0
2501     5411.0
9512     5411.0
11804    5912.0
9611     5411.0
14542    5912.0
12594    5912.0
17164    4131.0
13283    5411.0
16132    5912.0
2929     7011.0
19908    4131.0
1082     5411.0
Name: mcc, dtype: float64

In [54]:
merchants["mcc"].value_counts(dropna=False)

mcc
NaN         514
4131        435
7011        428
4814        419
5311        418
5699        410
5812        405
5411        402
5912        390
5999        381
5942        374
misc         99
UNKNOWN      80
05699        68
05912        68
05812        66
5311.0       62
05311        60
05411        59
05942        58
07011        58
5699.0       55
04131        55
5411.0       54
5942.0       53
5812.0       52
5912.0       52
4131.0       51
04814        50
05999        50
4814.0       49
MCC-4131     48
MCC-5999     48
5999.0       43
MCC-5311     40
MCC-5912     40
MCC-4814     39
MCC-5699     38
7011.0       36
MCC-7011     35
MCC-5942     28
MCC-5812     24
MCC-5411     16
Name: count, dtype: int64

In [55]:
def clean_mcc(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).strip().upper()

   
    x = x.replace("MCC-", "")
    x = x.replace("MCC", "")

    x = x.replace(" ", "")


    if x in ["", "MISC", "UNKNOWN", "NAN"]:
        return pd.NA


    try:
        x = float(x)
        return int(x)
    except:
        return pd.NA

In [56]:
merchants["mcc_clean"] = merchants["mcc"].apply(clean_mcc)

In [57]:
merchants["mcc_clean"].value_counts(dropna=False)

mcc_clean
<NA>    693
4131    589
5311    580
5699    571
7011    557
4814    557
5912    550
5812    547
5411    531
5999    522
5942    513
Name: count, dtype: int64

In [58]:
display(
    merchants[
        ["mcc_clean", "merchant_category"]
    ]
    .dropna(subset=["mcc_clean"])
    .drop_duplicates()
    .sort_values("mcc_clean")
)

     mcc_clean merchant_category
1117      4131          bus/taxi
48        4131            TRAVEL
43        4131         Transport
305       4131         transport
35        4131          transprt
...        ...               ...
977       7011             hotel
31        7011            Hotels
97        7011       Hospitality
2063      7011            hotels
0         7011     hotel_lodging

[82 rows x 2 columns]

In [59]:
mcc_category_map = {
    4131: "Transportation",
    4814: "Telecom",
    5311: "Department Stores",
    5411: "Grocery",
    5699: "Clothing",
    5812: "Food & Restaurants",
    5912: "Pharmacy & Medical",
    5942: "Books & Stationery",
    5999: "Other Retail",
    7011: "Hotels & Hospitality"
}

In [60]:
transactions_clean["mcc_clean"] = (
    transactions_clean["mcc"].apply(clean_mcc)
)

In [61]:
transactions_clean["mcc_clean"].value_counts(dropna=False)

mcc_clean
5411    5720
5912    2891
<NA>    2872
5812    2866
7011    2827
4131    2824
Name: count, dtype: int64

In [62]:
transactions_clean["merchant_category_clean"] = (
    transactions_clean["mcc_clean"]
    .map(mcc_category_map)
    .fillna("Unknown")
)

In [63]:
transactions_clean["merchant_category_clean"].value_counts()

merchant_category_clean
Grocery                 5720
Pharmacy & Medical      2891
Unknown                 2872
Food & Restaurants      2866
Hotels & Hospitality    2827
Transportation          2824
Name: count, dtype: int64

In [64]:
kyc.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 36400 entries, 0 to 36399
Data columns (total 13 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   user_id           36400 non-null  object
 1   full_name         36400 non-null  object
 2   pan               34504 non-null  object
 3   aadhaar           33736 non-null  object
 4   date_of_birth     33456 non-null  object
 5   city              36400 non-null  object
 6   state             36400 non-null  object
 7   monthly_income    33467 non-null  object
 8   occupation        36400 non-null  object
 9   signup_timestamp  33490 non-null  object
 10  kyc_status        36400 non-null  object
 11  risk_segment      36400 non-null  object
 12  user_id_clean     36400 non-null  object
dtypes: object(13)
memory usage: 3.6+ MB

In [65]:
kyc.head(10)

     user_id        full_name         pan  ... kyc_status risk_segment user_id_clean
0   USR16112  Dhriti Deshmukh  SEJAA8194O  ...       Done          LOW      USR16112
1   USR17216       Megha Jani  QT0ZZ5561X  ...   Verified       medium      USR17216
2  USR 45454       PANINI LAL  QCNTL9489O  ...    Pending         High      USR45454
3   USR46189      Jack Parikh  RRVUI4059Q  ...   VERIFIED          low      USR46189
4   USR85256         Eta Ravi  ygvoi9236w  ...   APPROVED          LOW      USR85256
5  USR 20918       Vanya Chad  jdgoh0074y  ...   REJECTED       MEDIUM      USR20918
6   usr22494     NIRJA SHETTY  JWZVO4240H  ...     Reject       medium      USR22494
7   USR34742         Ati Dash  OOQCG9609N  ...   APPROVED         high      USR34742
8   USR83137         ria kale         NaN  ...    Pending          low      USR83137
9   USR99161   jalsa malhotra  QLSKS5105S  ...   Rejected          Low      USR99161

[10 rows x 13 columns]

In [66]:
kyc.isna().sum()

user_id                0
full_name              0
pan                 1896
aadhaar             2664
date_of_birth       2944
city                   0
state                  0
monthly_income      2933
occupation             0
signup_timestamp    2910
kyc_status             0
risk_segment           0
user_id_clean          0
dtype: int64

In [67]:
kyc["kyc_status"].value_counts(dropna=False)

kyc_status
Verified        4862
APPROVED        4706
VERIFIED        4601
KYC_DONE        4587
V               4554
Done            4454
PENDING         1465
Pending         1032
P               1003
IN_PROGRESS      984
Under Review     983
Rejected         923
R                611
REJECTED         562
Reject           547
FAILED           526
Name: count, dtype: int64

In [68]:
def clean_kyc_status(x):
    if pd.isna(x):
        return "UNKNOWN"

    x = str(x).strip().upper()

    if x in ["VERIFIED", "APPROVED", "KYC_DONE", "V", "DONE"]:
        return "APPROVED"

    elif x in ["PENDING", "P"]:
        return "PENDING"

    elif x in ["IN_PROGRESS", "UNDER REVIEW"]:
        return "IN_PROGRESS"

    elif x in ["REJECTED", "REJECT", "R", "FAILED"]:
        return "REJECTED"

    else:
        return "UNKNOWN"

In [69]:
kyc["kyc_status_clean"] = (
    kyc["kyc_status"].apply(clean_kyc_status)
)

In [70]:
kyc["kyc_status_clean"].value_counts()

kyc_status_clean
APPROVED       27764
PENDING         3500
REJECTED        3169
IN_PROGRESS     1967
Name: count, dtype: int64

In [71]:
kyc["risk_segment"].value_counts(dropna=False)

risk_segment
low        7022
LOW        7001
Low        6947
medium     3308
MEDIUM     3308
Medium     3227
High       1260
high       1256
HIGH       1205
UNKNOWN     656
unknown     625
Unknown     585
Name: count, dtype: int64

In [72]:
def clean_risk_segment(x):
    if pd.isna(x):
        return "UNKNOWN"

    x = str(x).strip().upper()

    if x in ["LOW", "MEDIUM", "HIGH"]:
        return x

    return "UNKNOWN"

In [73]:
kyc["risk_segment_clean"] = (
    kyc["risk_segment"].apply(clean_risk_segment)
)

In [74]:
kyc["risk_segment_clean"].value_counts()

risk_segment_clean
LOW        20970
MEDIUM      9843
HIGH        3721
UNKNOWN     1866
Name: count, dtype: int64

In [75]:
kyc["pan"].dropna().sample(30, random_state=42)

23221      GEWTF5037Y
17493       ZGWNU9654
5739       TGYHC2838L
7642       YHDVS2437V
9043       EOJVM2081B
27282      ZZNPC7917I
28691      PWQQA3272V
19412      NUSDN9284A
23511      IIKRS7005O
31492      JHANN0411S
4517     VJBJH 7371 F
13941      KONSP3994B
11408    QHHBP-2379-N
13913      MQHSL3876T
30730    FKTGA 5812 V
3844       LUEMJ4656L
5058       OVBRY5982C
30582      LSXWR1628F
12656      ETCZW7493Q
1781        HVMQA6101
8020        RIKNY4397
8290     UEMMC-3658-E
30359      KFGDL8756F
23802      TUTEI3621H
4416       QAZEN8394I
32618      avxpc6046i
6100       CXCAF8558R
29545    BVOZA 9552 E
14031      YWCKX2350P
34442      CVJUP6985J
Name: pan, dtype: object

In [76]:
kyc["pan"].astype(str).str.len().value_counts().sort_index()

pan
3      1896
9      1827
10    27622
12     5055
Name: count, dtype: int64

In [77]:
def clean_pan(x):
    if pd.isna(x):
        return pd.NA
    
    x = str(x).strip().upper()
    
    # Remove spaces and hyphens
    x = x.replace(" ", "")
    x = x.replace("-", "")
    
    return x

In [78]:
kyc["pan_clean"] = kyc["pan"].apply(clean_pan)

In [79]:
kyc[["pan", "pan_clean"]].head(20)

             pan   pan_clean
0     SEJAA8194O  SEJAA8194O
1     QT0ZZ5561X  QT0ZZ5561X
2     QCNTL9489O  QCNTL9489O
3     RRVUI4059Q  RRVUI4059Q
4     ygvoi9236w  YGVOI9236W
5     jdgoh0074y  JDGOH0074Y
6     JWZVO4240H  JWZVO4240H
7     OOQCG9609N  OOQCG9609N
8            NaN        <NA>
9     QLSKS5105S  QLSKS5105S
10  CACWZ 2722 S  CACWZ2722S
11  AIWTB 3506 U  AIWTB3506U
12     KWLPY9915   KWLPY9915
13    VGLXS2856D  VGLXS2856D
14  HLNXD 7947 Q  HLNXD7947Q
15    SIBUO4381D  SIBUO4381D
16    MFDIC1823G  MFDIC1823G
17    CXBKD3190N  CXBKD3190N
18    ufleh5366c  UFLEH5366C
19  MXMQW-7893-W  MXMQW7893W

In [80]:
kyc["missing_pan_flag"] = (
    kyc["pan_clean"].isna()
).astype(int)

In [81]:
kyc["missing_pan_flag"].value_counts()

missing_pan_flag
0    34504
1     1896
Name: count, dtype: int64

In [82]:
pan_pattern = r"^[A-Z]{5}[0-9]{4}[A-Z]$"

kyc["invalid_pan_flag"] = (
    kyc["pan_clean"].notna()
    & ~kyc["pan_clean"].str.match(pan_pattern, na=False)
).astype(int)

In [83]:
kyc["invalid_pan_flag"].value_counts()

invalid_pan_flag
0    33754
1     2646
Name: count, dtype: int64

In [84]:
display(
    kyc[
        kyc["invalid_pan_flag"] == 1
    ][["pan", "pan_clean"]].head(20)
)

            pan   pan_clean
1    QT0ZZ5561X  QT0ZZ5561X
12    KWLPY9915   KWLPY9915
58    QPZXB2641   QPZXB2641
62   RWL1L9015J  RWL1L9015J
110   UWTIE0098   UWTIE0098
111   IRKEM1603   IRKEM1603
113  RCL1Y8260J  RCL1Y8260J
130  0WYDK8338N  0WYDK8338N
133   YBWWC3453   YBWWC3453
155   SGQUO5647   SGQUO5647
192  MVX0X7597Z  MVX0X7597Z
196  RAE1D7695D  RAE1D7695D
219   OSBRG1438   OSBRG1438
226   RUCYJ0962   RUCYJ0962
227   WITWZ1703   WITWZ1703
237   OESTA4426   OESTA4426
248  XH0L16368X  XH0L16368X
260   RJHXX9084   RJHXX9084
273  UX0GH6864Q  UX0GH6864Q
284   KDCRY0004   KDCRY0004

In [85]:
kyc["invalid_pan_flag"].value_counts()

invalid_pan_flag
0    33754
1     2646
Name: count, dtype: int64

In [86]:
kyc["aadhaar"].dropna().sample(30, random_state=42)

28333      888216320691
2934       902498501073
31564      089647682915
5985       939280360696
35192      805952220097
12008    XXXX-XXXX-3091
9452     9202 1772 5180
10285    5054-4793-9538
19998      228543393925
2153       698681409434
33999        6135063010
24470    XXXX-XXXX-5236
6808     1367-8705-0747
13915      434198352494
2485     8123 5182 9572
6709       801913467053
8297       698967858478
20648    4451 5148 8567
12154    0199 9564 3976
28260    8184 8338 5108
21375      813280120466
27282      985463187928
23791    5635 4003 0977
12970      012024085465
13081    2123-7447-1979
27453    2617 1962 8807
32451      775075798159
31815      895646899459
12633      661736750900
18918      086421764656
Name: aadhaar, dtype: object

In [87]:
kyc["aadhaar"].isna().sum()

np.int64(2664)

In [88]:
kyc["aadhaar"].astype(str).str.len().value_counts().sort_index()

aadhaar
3      2664
10     1741
12    16372
13     1520
14    14103
Name: count, dtype: int64

In [89]:
def clean_aadhaar(x):
    if pd.isna(x):
        return pd.NA
    
    x = str(x).strip().upper()
    
    # Remove spaces and hyphens
    x = x.replace(" ", "")
    x = x.replace("-", "")
    
    return x

In [90]:
kyc["aadhaar_clean"] = kyc["aadhaar"].apply(clean_aadhaar)

In [91]:
display(
    kyc[["aadhaar", "aadhaar_clean"]].head(20)
)

           aadhaar  aadhaar_clean
0     715658320763   715658320763
1     023412025028   023412025028
2   2781 6299 9816   278162999816
3   0667 8032 7731   066780327731
4     176258817110   176258817110
5     894463789078   894463789078
6    5277136337802  5277136337802
7     985048780290   985048780290
8    4902616251043  4902616251043
9     944300371193   944300371193
10  0179 7994 0718   017979940718
11   2501336722102  2501336722102
12    577479489696   577479489696
13  6244-9453-8280   624494538280
14    846950176261   846950176261
15    448832778808   448832778808
16  XXXX-XXXX-5406   XXXXXXXX5406
17    976073035125   976073035125
18             NaN           <NA>
19  XXXX-XXXX-1365   XXXXXXXX1365

In [92]:
kyc["missing_aadhaar_flag"] = (
    kyc["aadhaar_clean"].isna()
).astype(int)

In [93]:
kyc["masked_aadhaar_flag"] = (
    kyc["aadhaar_clean"]
    .fillna("")
    .str.contains("X", regex=False)
).astype(int)

In [94]:
aadhaar_pattern = r"^\d{12}$"

kyc["invalid_aadhaar_flag"] = (
    kyc["aadhaar_clean"].notna()
    & (kyc["masked_aadhaar_flag"] == 0)
    & ~kyc["aadhaar_clean"].str.match(
        aadhaar_pattern,
        na=False
    )
).astype(int)

In [95]:
kyc["missing_aadhaar_flag"].value_counts()

missing_aadhaar_flag
0    33736
1     2664
Name: count, dtype: int64

In [96]:
kyc["masked_aadhaar_flag"].value_counts()

masked_aadhaar_flag
0    33478
1     2922
Name: count, dtype: int64

In [97]:
kyc["invalid_aadhaar_flag"].value_counts()

invalid_aadhaar_flag
0    33139
1     3261
Name: count, dtype: int64

In [98]:
kyc["date_of_birth"].dropna().sample(30, random_state=42)

27794             1079729536
13096             07-15-1984
23888             11-13-1985
8124              2004/04/23
23912             1979/09/25
12499    21/05/1996 07:09 PM
22451             05-10-1991
23609             1123471296
5309             28-Aug-1963
1484              02-19-2006
19767             1988/01/21
5216     28/02/1961 07:35 AM
22805    10/05/1966 05:41 PM
4134             27-May-2005
988               13/06/1987
24306    04/09/1964 03:38 AM
9678              24/12/1994
5292     01/05/1993 01:02 PM
33888             07-14-2000
16383             1086214864
31464             13/10/2005
1057             27-Oct-1960
8649     14/12/1968 12:35 AM
18337             1998/06/17
8557              1134603629
15560             26/09/1983
17254             11/05/2003
11555             19/01/1991
3172     1981-11-20 23:20:16
35943             1990/11/23
Name: date_of_birth, dtype: object

In [99]:
kyc["date_of_birth"].isna().sum()

np.int64(2944)

In [100]:
kyc["date_of_birth"].astype(str).str.len().value_counts().sort_index()

date_of_birth
3      2944
6         3
7        12
8       190
9      1811
10    17580
11     5033
19     8827
Name: count, dtype: int64

In [101]:
def clean_dob(x):
    if pd.isna(x):
        return pd.NaT

    x = str(x).strip()

    # Unix timestamp, including positive and negative values
    if x.lstrip("-").isdigit():
        return pd.to_datetime(
            int(x),
            unit="s",
            errors="coerce"
        )

    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
        "%Y/%m/%d",
        "%d/%m/%Y %I:%M %p",
        "%d/%m/%Y",
        "%m-%d-%Y %I:%M:%S %p",
        "%m-%d-%Y",
        "%d-%b-%Y",
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            pass

    return pd.NaT

In [102]:
kyc["date_of_birth_clean"] = (
    kyc["date_of_birth"].apply(clean_dob)
)

In [103]:
kyc["date_of_birth_clean"].isna().sum()

np.int64(2944)

In [104]:
display(
    kyc[
        ["date_of_birth", "date_of_birth_clean"]
    ].head(30)
)

          date_of_birth date_of_birth_clean
0   06/04/1967 12:14 AM 1967-04-06 00:14:00
1                   NaN                 NaT
2                   NaN                 NaT
3                   NaN                 NaT
4   1969-02-19 08:25:23 1969-02-19 08:25:23
5            20/04/1961 1961-04-20 00:00:00
6           05-Sep-1990 1990-09-05 00:00:00
7            12-20-1962 1962-12-20 00:00:00
8           09-Sep-2005 2005-09-09 00:00:00
9   20/05/1963 05:27 AM 1963-05-20 05:27:00
10                  NaN                 NaT
11           2003/06/16 2003-06-16 00:00:00
12           27/05/1982 1982-05-27 00:00:00
13  1977-04-17 07:18:29 1977-04-17 07:18:29
14  24/08/1969 03:28 AM 1969-08-24 03:28:00
15  1968-09-20 20:31:53 1968-09-20 20:31:53
16          15-Jul-1987 1987-07-15 00:00:00
17            809571887 1995-08-28 01:04:47
18           16/07/1998 1998-07-16 00:00:00
19           26/04/1999 1999-04-26 00:00:00
20           06-02-1967 1967-06-02 00:00:00
21           1966/07/04 1966-07-04 00:00:00
22  10/09/1993 01:31 PM 1993-09-10 13:31:00
23           01-18-1964 1964-01-18 00:00:00
24           06-09-1978 1978-06-09 00:00:00
25           25/08/2004 2004-08-25 00:00:00
26           09/01/1987 1987-01-09 00:00:00
27           29/07/1983 1983-07-29 00:00:00
28           13/02/1990 1990-02-13 00:00:00
29           23/09/2003 2003-09-23 00:00:00

In [105]:
dob_failed = kyc[
    kyc["date_of_birth"].notna() &
    kyc["date_of_birth_clean"].isna()
]

display(
    dob_failed[["date_of_birth"]].head(50)
)

Empty DataFrame
Columns: [date_of_birth]
Index: []

In [106]:
dob_failed["date_of_birth"].astype(str).value_counts().head(30)

Series([], Name: count, dtype: int64)

In [107]:
kyc["date_of_birth_clean"].isna().sum()

np.int64(2944)

In [108]:
print(kyc["date_of_birth_clean"].min())
print(kyc["date_of_birth_clean"].max())

1960-01-01 09:04:52
2007-12-30 00:00:00

In [109]:
display(
    kyc[
        ["date_of_birth", "date_of_birth_clean"]
    ].sample(30, random_state=42)
)

             date_of_birth date_of_birth_clean
21616           23/12/1981 1981-12-23 00:00:00
11710           30/11/1998 1998-11-30 00:00:00
30145           04/01/2003 2003-01-04 00:00:00
13832           28/09/2007 2007-09-28 00:00:00
27742  1960-12-30 19:43:25 1960-12-30 19:43:25
14206           1996/11/15 1996-11-15 00:00:00
31532                  NaN                 NaT
8824            1995/07/23 1995-07-23 00:00:00
8135   19/06/1972 05:55 PM 1972-06-19 17:55:00
31962           1992/04/06 1992-04-06 00:00:00
5598           03-Jul-1967 1967-07-03 00:00:00
23436          14-Jul-1992 1992-07-14 00:00:00
5754            07-28-1999 1999-07-28 00:00:00
83     28/11/1998 03:44 PM 1998-11-28 15:44:00
26000           30/01/1966 1966-01-30 00:00:00
1732            04-25-2005 2005-04-25 00:00:00
21314           24/12/1972 1972-12-24 00:00:00
23422            327512916 1980-05-18 15:48:36
7029            22/05/2003 2003-05-22 00:00:00
3785           29-May-1973 1973-05-29 00:00:00
11313  12/11/1982 06:49 AM 1982-11-12 06:49:00
2135           29-Dec-1999 1999-12-29 00:00:00
6319           05-Mar-1987 1987-03-05 00:00:00
30479          11-Apr-1983 1983-04-11 00:00:00
31874  14/12/2006 01:43 AM 2006-12-14 01:43:00
33103           16/08/1981 1981-08-16 00:00:00
14858          26-Jul-2006 2006-07-26 00:00:00
24537  20/07/2003 04:12 AM 2003-07-20 04:12:00
6215   01/02/1995 08:40 PM 1995-02-01 20:40:00
28678           2000/07/16 2000-07-16 00:00:00

In [110]:
kyc["missing_dob_flag"] = (
    kyc["date_of_birth_clean"].isna()
).astype(int)

In [111]:
today = pd.Timestamp("2026-09-15")

kyc["invalid_dob_flag"] = (
    kyc["date_of_birth_clean"].notna()
    & (
        (kyc["date_of_birth_clean"] > today)
        | (kyc["date_of_birth_clean"] < pd.Timestamp("1900-01-01"))
    )
).astype(int)

In [112]:
print("Missing DOB:", kyc["missing_dob_flag"].sum())
print("Invalid DOB:", kyc["invalid_dob_flag"].sum())

Missing DOB: 2944
Invalid DOB: 0

In [113]:
def clean_income(x):
    if pd.isna(x):
        return np.nan

    x = str(x).strip().upper()

    # Remove currency symbols/text
    x = x.replace("₹", "")
    x = x.replace("INR", "")
    x = x.replace("RS.", "")
    x = x.replace("RS", "")

    # Remove commas
    x = x.replace(",", "")

    # Handle values like 27.3K
    if x.endswith("K"):
        try:
            return float(x[:-1]) * 1000
        except:
            return np.nan

    return pd.to_numeric(x, errors="coerce")

In [114]:
kyc["monthly_income_clean"] = (
    kyc["monthly_income"].apply(clean_income)
)

In [115]:
kyc["missing_income_flag"] = (
    kyc["monthly_income_clean"].isna()
).astype(int)

kyc["negative_income_flag"] = (
    kyc["monthly_income_clean"] < 0
).astype(int)

kyc["invalid_income_flag"] = (
    kyc["monthly_income_clean"].isna()
    & kyc["monthly_income"].notna()
).astype(int)

In [116]:
print("Missing income:", kyc["missing_income_flag"].sum())
print("Negative income:", kyc["negative_income_flag"].sum())
print("Invalid income:", kyc["invalid_income_flag"].sum())

Missing income: 4723
Negative income: 1456
Invalid income: 1790

In [117]:
display(
    kyc[[
        "monthly_income",
        "monthly_income_clean",
        "negative_income_flag",
        "invalid_income_flag"
    ]].sample(30, random_state=42)
)

      monthly_income  ...  invalid_income_flag
21616         104774  ...                    0
11710          -9103  ...                    0
30145          44045  ...                    0
13832          36384  ...                    0
27742            NaN  ...                    0
14206        ₹71,859  ...                    0
31532  Not Available  ...                    1
8824             NaN  ...                    0
8135           41026  ...                    0
31962        ₹15,389  ...                    0
5598          -27956  ...                    0
23436     Rs. 40,250  ...                    0
5754         ₹23,140  ...                    0
83           ₹23,001  ...                    0
26000     INR 35,405  ...                    0
1732           26673  ...                    0
21314          12904  ...                    0
23422          10935  ...                    0
7029      Rs. 31,579  ...                    0
3785      INR 25,326  ...                    0
11313            NaN  ...                    0
2135             NaN  ...                    0
6319      INR 23,547  ...                    0
30479     Rs. 72,719  ...                    0
31874          15014  ...                    0
33103          24606  ...                    0
14858           9301  ...                    0
24537     INR 23,306  ...                    0
6215           36356  ...                    0
28678        ₹13,915  ...                    0

[30 rows x 4 columns]

In [118]:
print(kyc["signup_timestamp"].head(30).to_string())

0     2025-12-02 02:18:16
1              01-31-2024
2     2026-01-30 23:57:18
3              09-04-2025
4             03-Feb-2026
5              25/04/2024
6                     NaN
7              07-25-2025
8              03/04/2024
9                     NaN
10            08-Mar-2026
11    2024-05-24 07:29:05
12             16/02/2024
13            30-Jan-2024
14             1752135790
15    2024-01-03 00:50:12
16    2025-04-06 14:45:00
17            30-Dec-2024
18             2025/10/12
19             04-06-2024
20             2026/01/12
21            12-Feb-2026
22             02-18-2024
23             11/10/2024
24    2026-02-06 04:09:04
25    2025-09-08 15:25:17
26    10/11/2024 04:26 PM
27             16/02/2025
28             2026/03/08
29             1719640264

In [119]:
print("Missing signup timestamp:", kyc["signup_timestamp"].isna().sum())

Missing signup timestamp: 2910

In [120]:
print(kyc["signup_timestamp"].value_counts().head(20))

signup_timestamp
13/04/2024     21
07/01/2025     18
23/01/2026     17
2025/11/22     16
05/02/2026     16
02/03/2025     16
2025/01/03     16
27/03/2025     15
16/10/2024     15
25/01/2025     15
01/10/2025     15
20/12/2025     15
13/10/2024     15
2024/01/10     15
01-Sep-2025    15
11-18-2024     14
03/03/2026     14
16/05/2024     14
06/05/2025     14
06-13-2024     14
Name: count, dtype: int64

In [121]:
def clean_signup_timestamp(x):
    if pd.isna(x):
        return pd.NaT

    x = str(x).strip()

    # Handle Unix timestamp, including negative values
    if x.lstrip("-").isdigit() and len(x.lstrip("-")) >= 9:
        return pd.to_datetime(
            int(x),
            unit="s",
            errors="coerce"
        )

    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",

        "%d/%m/%Y %I:%M %p",
        "%d/%m/%Y",

        "%d-%m-%Y %I:%M %p",
        "%d-%m-%Y",

        "%m-%d-%Y %I:%M %p",
        "%m-%d-%Y",

        "%Y/%m/%d %H:%M:%S",
        "%Y/%m/%d",

        "%d-%b-%Y %H:%M:%S",
        "%d-%b-%Y",

        "%d-%B-%Y %H:%M:%S",
        "%d-%B-%Y",
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            pass

    return pd.NaT

In [122]:
kyc["signup_timestamp_clean"] = (
    kyc["signup_timestamp"].apply(clean_signup_timestamp)
)

In [123]:
print(
    "Missing original:",
    kyc["signup_timestamp"].isna().sum()
)

print(
    "Missing after cleaning:",
    kyc["signup_timestamp_clean"].isna().sum()
)

Missing original: 2910
Missing after cleaning: 2910

In [124]:
kyc["missing_signup_timestamp_flag"] = (
    kyc["signup_timestamp_clean"].isna()
).astype(int)

In [125]:
today = pd.Timestamp("2026-09-15")

kyc["invalid_signup_timestamp_flag"] = (
    kyc["signup_timestamp_clean"].notna()
    & (
        (kyc["signup_timestamp_clean"] > today)
        | (
            kyc["signup_timestamp_clean"]
            < pd.Timestamp("2020-01-01")
        )
    )
).astype(int)

In [126]:
print(
    "Missing signup timestamp:",
    kyc["missing_signup_timestamp_flag"].sum()
)

print(
    "Invalid signup timestamp:",
    kyc["invalid_signup_timestamp_flag"].sum()
)

Missing signup timestamp: 2910
Invalid signup timestamp: 61

In [127]:
display(
    kyc.loc[
        kyc["invalid_signup_timestamp_flag"] == 1,
        ["user_id", "signup_timestamp", "signup_timestamp_clean"]
    ].sort_values("signup_timestamp_clean")
)

        user_id signup_timestamp signup_timestamp_clean
5758   usr33224       01-10-2026             2026-10-01
16976  usr33224       01-10-2026             2026-10-01
8829   USR10651       01-10-2026             2026-10-01
20231     91255       01-10-2026             2026-10-01
27965  USR26843       01-10-2026             2026-10-01
...         ...              ...                    ...
1110   usr54586       03-12-2026             2026-12-03
24472  USR86427       03-12-2026             2026-12-03
23662  USR13991       03-12-2026             2026-12-03
29128  USR95912       03-12-2026             2026-12-03
6653   USR97236       03-12-2026             2026-12-03

[61 rows x 3 columns]

In [128]:
print(
    kyc.loc[
        kyc["invalid_signup_timestamp_flag"] == 1,
        "signup_timestamp_clean"
    ].describe()
)

count                               61
mean     2026-10-30 12:35:24.590163968
min                2026-10-01 00:00:00
25%                2026-10-02 00:00:00
50%                2026-11-01 00:00:00
75%                2026-12-02 00:00:00
max                2026-12-03 00:00:00
Name: signup_timestamp_clean, dtype: object

In [129]:
kyc["future_signup_flag"] = (
    kyc["signup_timestamp_clean"] > pd.Timestamp("2026-09-15")
).astype(int)

In [130]:
kyc.drop(
    columns=["invalid_signup_timestamp_flag"],
    inplace=True
)

In [131]:
print("Missing signup timestamp:", kyc["missing_signup_timestamp_flag"].sum())
print("Future signup dates:", kyc["future_signup_flag"].sum())

Missing signup timestamp: 2910
Future signup dates: 61

In [132]:
print(kyc["city"].value_counts().to_string())

city
pune         1073
HYDERABAD    1062
Amritsar     1060
ludhiana     1043
LDH          1040
Poona        1039
Ludhiana     1037
Lucknow      1034
kolkata      1032
Hyderabad    1031
Jalandar     1021
Hyd          1019
Jalandhar    1008
Chennai      1008
LKO          1003
jaipur        998
Calcutta      994
chennai       993
JPR           986
lucknow       982
ASR           980
jalandhar     974
Pune          970
Jaipur        970
amritsar      953
Kolkata       953
Madras        928
BLR           829
Bangalore     743
bengaluru     736
Bengaluru     722
Mumbay        637
DELHI         633
New Delhi     631
delhi         628
Bombay        627
Dilli         620
MUMBAI        620
Delhi         604
Mumbai        591
mumbai        588

In [133]:
print(kyc["state"].value_counts().to_string())

state
Punjab           9116
Maharashtra      6145
Delhi            3116
Telangana        3112
Karnataka        3030
Uttar Pradesh    3019
West Bengal      2979
Rajasthan        2954
Tamil Nadu       2929

In [134]:
print(kyc["occupation"].value_counts().to_string())

occupation
Unemployed        4160
Freelancer        4087
Student           4080
Self Employed     4070
Business Owner    4049
Farmer            4045
Retired           4036
Salaried          3943
Gig Worker        3930

In [135]:
def clean_city(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).strip().upper()

    city_map = {
        "PUNE": "Pune",
        "POONA": "Pune",

        "LUDHIANA": "Ludhiana",
        "LDH": "Ludhiana",

        "HYDERABAD": "Hyderabad",
        "HYD": "Hyderabad",

        "JALANDHAR": "Jalandhar",
        "JALANDAR": "Jalandhar",

        "LUCKNOW": "Lucknow",
        "LKO": "Lucknow",

        "JAIPUR": "Jaipur",
        "JPR": "Jaipur",

        "KOLKATA": "Kolkata",
        "CALCUTTA": "Kolkata",

        "DELHI": "Delhi",
        "DILLI": "Delhi",
        "NEW DELHI": "Delhi",

        "MUMBAI": "Mumbai",
        "BOMBAY": "Mumbai",
        "MUMBAY": "Mumbai",

        "CHENNAI": "Chennai",
        "MADRAS": "Chennai",

        "BENGALURU": "Bengaluru",
        "BANGALORE": "Bengaluru",
        "BLR": "Bengaluru",

        "AMRITSAR": "Amritsar",
        "ASR": "Amritsar",
    }

    return city_map.get(x, x.title())

In [136]:
kyc["city_clean"] = kyc["city"].apply(clean_city)

In [137]:
print(kyc["city_clean"].value_counts().to_string())

city_clean
Ludhiana     3120
Delhi        3116
Hyderabad    3112
Pune         3082
Mumbai       3063
Bengaluru    3030
Lucknow      3019
Jalandhar    3003
Amritsar     2993
Kolkata      2979
Jaipur       2954
Chennai      2929

In [138]:
print("Unique cities before:", kyc["city"].nunique())
print("Unique cities after:", kyc["city_clean"].nunique())

Unique cities before: 41
Unique cities after: 12

In [139]:
kyc["state_clean"] = (
    kyc["state"]
    .astype("string")
    .str.strip()
    .str.upper()
    .str.title()
)

In [140]:
print("Unique states before:", kyc["state"].nunique())
print("Unique states after:", kyc["state_clean"].nunique())

print("\nState distribution:")
print(kyc["state_clean"].value_counts().to_string())

Unique states before: 9
Unique states after: 9

State distribution:
state_clean
Punjab           9116
Maharashtra      6145
Delhi            3116
Telangana        3112
Karnataka        3030
Uttar Pradesh    3019
West Bengal      2979
Rajasthan        2954
Tamil Nadu       2929

In [141]:
kyc["occupation_clean"] = (
    kyc["occupation"]
    .astype("string")
    .str.strip()
    .str.replace(r"\s+", " ", regex=True)
    .str.title()
)

In [142]:
print("Unique occupations before:", kyc["occupation"].nunique())
print("Unique occupations after:", kyc["occupation_clean"].nunique())

print("\nOccupation distribution:")
print(kyc["occupation_clean"].value_counts().to_string())

Unique occupations before: 9
Unique occupations after: 9

Occupation distribution:
occupation_clean
Unemployed        4160
Freelancer        4087
Student           4080
Self Employed     4070
Business Owner    4049
Farmer            4045
Retired           4036
Salaried          3943
Gig Worker        3930

In [143]:
print(
    "Total KYC rows:",
    len(kyc)
)

print(
    "Unique cleaned users:",
    kyc["user_id_clean"].nunique()
)

print(
    "Duplicate cleaned user rows:",
    kyc["user_id_clean"].duplicated(keep=False).sum()
)

Total KYC rows: 36400
Unique cleaned users: 29355
Duplicate cleaned user rows: 13025

In [144]:
duplicate_users = (
    kyc[
        kyc["user_id_clean"].duplicated(keep=False)
    ]
    .sort_values("user_id_clean")
)

display(
    duplicate_users[
        [
            "user_id",
            "user_id_clean",
            "full_name",
            "pan_clean",
            "aadhaar_clean",
            "date_of_birth_clean",
            "monthly_income_clean",
            "kyc_status_clean",
            "risk_segment_clean"
        ]
    ].head(50)
)

      user_id user_id_clean  ... kyc_status_clean risk_segment_clean
13127   10098         10098  ...         REJECTED                LOW
949     10098         10098  ...         REJECTED                LOW
3873    11301         11301  ...         REJECTED             MEDIUM
27756   11301         11301  ...         REJECTED             MEDIUM
26409   11947         11947  ...         REJECTED                LOW
21625   11947         11947  ...      IN_PROGRESS             MEDIUM
5451    12173         12173  ...         APPROVED             MEDIUM
6254    12173         12173  ...         REJECTED             MEDIUM
34833   16969         16969  ...         APPROVED                LOW
28573   16969         16969  ...         APPROVED                LOW
249     17255         17255  ...      IN_PROGRESS                LOW
32159   17255         17255  ...          PENDING                LOW
11310   21292         21292  ...         APPROVED                LOW
21351   21292         21292  ...          PENDING                LOW
15445   23776         23776  ...         APPROVED                LOW
12939   23776         23776  ...         APPROVED                LOW
16379   24005         24005  ...         APPROVED                LOW
7885    24005         24005  ...         APPROVED                LOW
3294    25377         25377  ...          PENDING               HIGH
14353   25377         25377  ...         REJECTED               HIGH
4000    25446         25446  ...         APPROVED            UNKNOWN
20164   25446         25446  ...         APPROVED            UNKNOWN
28796   25581         25581  ...         APPROVED                LOW
15921   25581         25581  ...         APPROVED                LOW
2605    26602         26602  ...         APPROVED                LOW
828     26602         26602  ...          PENDING                LOW
13303   27892         27892  ...      IN_PROGRESS             MEDIUM
21412   27892         27892  ...         REJECTED             MEDIUM
14310   28288         28288  ...         APPROVED                LOW
34235   28288         28288  ...         APPROVED                LOW
3154    30710         30710  ...         APPROVED             MEDIUM
21150   30710         30710  ...         REJECTED             MEDIUM
19723   30840         30840  ...         APPROVED               HIGH
4024    30840         30840  ...         APPROVED               HIGH
15113   32252         32252  ...         REJECTED                LOW
4861    32252         32252  ...         APPROVED                LOW
22086   35009         35009  ...          PENDING                LOW
20767   35009         35009  ...          PENDING                LOW
11089   35009         35009  ...         APPROVED                LOW
4584    35093         35093  ...         APPROVED                LOW
34900   35093         35093  ...          PENDING                LOW
21628   37858         37858  ...         APPROVED                LOW
11190   37858         37858  ...         APPROVED                LOW
11901   40148         40148  ...         APPROVED             MEDIUM
16157   40148         40148  ...         APPROVED                LOW
14273   43692         43692  ...         APPROVED                LOW
76      43692         43692  ...         APPROVED                LOW
34608   47186         47186  ...         APPROVED                LOW
32331   47186         47186  ...          PENDING                LOW
8766    47224         47224  ...         REJECTED                LOW

[50 rows x 9 columns]

In [145]:
kyc_exact_duplicates = kyc.drop_duplicates().shape[0]

print("Rows:", len(kyc))
print("Unique complete rows:", kyc.drop_duplicates().shape[0])
print(
    "Exact duplicate rows:",
    len(kyc) - kyc.drop_duplicates().shape[0]
)

Rows: 36400

Unique complete rows: 36122
Exact duplicate rows: 278

In [146]:
kyc_clean = kyc.drop_duplicates().copy()

In [147]:
print("Original KYC rows:", len(kyc))
print("After exact duplicate removal:", len(kyc_clean))

Original KYC rows: 36400
After exact duplicate removal: 36122

In [148]:
print("KYC clean rows:", len(kyc_clean))
print("Unique users:", kyc_clean["user_id_clean"].nunique())
print(
    "Rows belonging to duplicate users:",
    kyc_clean["user_id_clean"].duplicated(keep=False).sum()
)

KYC clean rows: 36122
Unique users: 29355
Rows belonging to duplicate users: 12565

In [149]:
duplicate_counts = (
    kyc_clean["user_id_clean"]
    .value_counts()
)

print(
    duplicate_counts[duplicate_counts > 1]
    .value_counts()
    .sort_index()
)

count
2    4935
3     763
4      94
5       6
Name: count, dtype: int64

In [150]:
status_conflicts = (
    kyc_clean
    .groupby("user_id_clean")["kyc_status_clean"]
    .nunique()
)

print(
    "Users with conflicting KYC statuses:",
    (status_conflicts > 1).sum()
)

Users with conflicting KYC statuses: 2677

In [151]:
name_conflicts = (
    kyc_clean
    .groupby("user_id_clean")["full_name"]
    .nunique()
)

print(
    "Users with multiple names:",
    (name_conflicts > 1).sum()
)

Users with multiple names: 4999

In [152]:
pan_conflicts = (
    kyc_clean
    .groupby("user_id_clean")["pan_clean"]
    .nunique()
)

print(
    "Users with multiple PANs:",
    (pan_conflicts > 1).sum()
)

Users with multiple PANs: 4554

In [153]:
def clean_name(x):
    if pd.isna(x):
        return pd.NA
    
    x = str(x).strip().upper()
    x = " ".join(x.split())   # remove extra spaces
    
    return x

kyc_clean["full_name_clean"] = kyc_clean["full_name"].apply(clean_name)

In [154]:
name_conflicts = (
    kyc_clean.groupby("user_id_clean")["full_name_clean"].nunique()
)

print("Users with conflicting names:",
      (name_conflicts > 1).sum())

Users with conflicting names: 4999

In [155]:
aadhaar_conflicts = (
    kyc_clean.groupby("user_id_clean")["aadhaar_clean"].nunique()
)

print("Users with multiple Aadhaar values:",
      (aadhaar_conflicts > 1).sum())

Users with multiple Aadhaar values: 4378

In [156]:
dob_conflicts = (
    kyc_clean.groupby("user_id_clean")["date_of_birth_clean"].nunique()
)

print("Users with conflicting DOBs:",
      (dob_conflicts > 1).sum())

Users with conflicting DOBs: 4314

In [157]:
# Number of distinct values for each identity/KYC field per user
status_n = kyc_clean.groupby("user_id_clean")["kyc_status_clean"].transform("nunique")
name_n = kyc_clean.groupby("user_id_clean")["full_name_clean"].transform("nunique")
pan_n = kyc_clean.groupby("user_id_clean")["pan_clean"].transform("nunique")
aadhaar_n = kyc_clean.groupby("user_id_clean")["aadhaar_clean"].transform("nunique")
dob_n = kyc_clean.groupby("user_id_clean")["date_of_birth_clean"].transform("nunique")

# Conflict flags
kyc_clean["kyc_status_conflict_flag"] = (status_n > 1).astype(int)
kyc_clean["name_conflict_flag"] = (name_n > 1).astype(int)
kyc_clean["pan_conflict_flag"] = (pan_n > 1).astype(int)
kyc_clean["aadhaar_conflict_flag"] = (aadhaar_n > 1).astype(int)
kyc_clean["dob_conflict_flag"] = (dob_n > 1).astype(int)

# Overall identity conflict score
kyc_clean["identity_conflict_score"] = (
    kyc_clean["name_conflict_flag"]
    + kyc_clean["pan_conflict_flag"]
    + kyc_clean["aadhaar_conflict_flag"]
    + kyc_clean["dob_conflict_flag"]
)

In [158]:
print(
    kyc_clean["identity_conflict_score"]
    .value_counts()
    .sort_index()
)

identity_conflict_score
0    25155
1       29
2      403
3     2741
4     7794
Name: count, dtype: int64

In [159]:
user_record_counts = (
    kyc_clean["user_id_clean"]
    .value_counts()
)

print(user_record_counts.value_counts().sort_index())

count
1    23557
2     4935
3      763
4       94
5        6
Name: count, dtype: int64

In [160]:
kyc_clean[
    kyc_clean["user_id_clean"].duplicated(keep=False)
][[
    "user_id_clean",
    "full_name_clean",
    "pan_clean",
    "aadhaar_clean",
    "date_of_birth_clean",
    "monthly_income_clean",
    "signup_timestamp_clean",
    "kyc_status_clean",
    "risk_segment_clean",
    "identity_conflict_score"
]].sort_values("user_id_clean").head(20)

      user_id_clean full_name_clean  ... risk_segment_clean identity_conflict_score
949           10098        XITI BEN  ...                LOW                       0
13127         10098        XITI BEN  ...                LOW                       0
27756         11301  BALJIWAN SINGH  ...             MEDIUM                       0
3873          11301  BALJIWAN SINGH  ...             MEDIUM                       0
21625         11947  CHATRESH MITRA  ...             MEDIUM                       4
26409         11947  TRIYA SACHDEVA  ...                LOW                       4
6254          12173     RANBIR VASA  ...             MEDIUM                       0
5451          12173     RANBIR VASA  ...             MEDIUM                       0
34833         16969    MICHAE1 SANT  ...                LOW                       0
28573         16969    MICHAE1 SANT  ...                LOW                       0
249           17255     ANUSHA PANT  ...                LOW                       0
32159         17255     ANUSHA PANT  ...                LOW                       0
21351         21292   MANBIR VAIDYA  ...                LOW                       0
11310         21292   MANBIR VAIDYA  ...                LOW                       0
15445         23776    RACHITA YOGI  ...                LOW                       3
12939         23776       OJAS TOOR  ...                LOW                       3
7885          24005        JAI DEEP  ...                LOW                       0
16379         24005        JAI DEEP  ...                LOW                       0
3294          25377    DALAJABUTALA  ...               HIGH                       0
14353         25377    DALAJABUTALA  ...               HIGH                       0

[20 rows x 10 columns]

In [161]:
id="n9v1kz"
# Check how many users have multiple records
multi_users = (
    kyc_clean["user_id_clean"]
    .value_counts()
)

multi_users = multi_users[multi_users > 1].index

# Look at duplicate users ordered by timestamp
kyc_clean[
    kyc_clean["user_id_clean"].isin(multi_users)
][[
    "user_id_clean",
    "signup_timestamp_clean",
    "kyc_status_clean",
    "identity_conflict_score",
    "kyc_status_conflict_flag"
]].sort_values(
    ["user_id_clean", "signup_timestamp_clean"]
).head(30)

      user_id_clean  ... kyc_status_conflict_flag
949           10098  ...                        0
13127         10098  ...                        0
3873          11301  ...                        0
27756         11301  ...                        0
26409         11947  ...                        1
21625         11947  ...                        1
5451          12173  ...                        1
6254          12173  ...                        1
28573         16969  ...                        0
34833         16969  ...                        0
249           17255  ...                        1
32159         17255  ...                        1
11310         21292  ...                        1
21351         21292  ...                        1
15445         23776  ...                        0
12939         23776  ...                        0
7885          24005  ...                        0
16379         24005  ...                        0
3294          25377  ...                        1
14353         25377  ...                        1
4000          25446  ...                        0
20164         25446  ...                        0
15921         25581  ...                        0
28796         25581  ...                        0
828           26602  ...                        1
2605          26602  ...                        1
13303         27892  ...                        1
21412         27892  ...                        1
14310         28288  ...                        0
34235         28288  ...                        0

[30 rows x 5 columns]

In [162]:
def clean_user_id_core(x):
    if pd.isna(x):
        return pd.NA
    x = str(x).strip().upper()
    x = x.replace(" ", "").replace("-", "").replace("_", "")
    if x.startswith("USR"):
        x = x[3:]
    if x.isdigit():
        return x
    return pd.NA

kyc_master = kyc_clean.copy()
kyc_master["user_id_core"] = kyc_master["user_id"].apply(clean_user_id_core)
kyc_master["kyc_record_count"] = (
    kyc_master.groupby("user_id_core")["user_id_core"].transform("size")
)

In [163]:
kyc_master = kyc_master.sort_values(
    ["user_id_core", "signup_timestamp_clean"]
)

In [164]:
kyc_master = (
    kyc_master.dropna(subset=["user_id_core"])
    .drop_duplicates("user_id_core", keep="last")
    .copy()
)

In [165]:
print("KYC history rows:", len(kyc_clean))
print("KYC master rows:", len(kyc_master))
print("Unique users:", kyc_master["user_id_clean"].nunique())

KYC history rows: 36122
KYC master rows: 28920
Unique users: 28920

In [166]:
matched_users = transactions_clean["user_id_clean"].isin(
    kyc_master["user_id_clean"]
)

print("Transactions:", len(transactions_clean))
print("Transactions with matching KYC:",
      matched_users.sum())
print("Transactions without matching KYC:",
      (~matched_users).sum())

Transactions: 20000
Transactions with matching KYC: 6189
Transactions without matching KYC: 13811

In [167]:
print("Sample transaction user IDs:")
print(transactions_clean["user_id_clean"].dropna().unique()[:20])

print("\nSample KYC user IDs:")
print(kyc_master["user_id_clean"].dropna().unique()[:20])

Sample transaction user IDs:
['USR45826' 'USR79397' 'USR87810' 'USR54287' 'USR53865' 'USR90546'
 'USR18691' 'USR16629' 'USR20899' 'USR51755' 'USR81003' 'USR70687'
 'USR37834' 'USR78386' 'USR21114' 'USR96222' 'USR13976' 'USR55935'
 'USR13890' 'USR15778']

Sample KYC user IDs:
['USR10001' 'USR10007' 'USR10010' 'USR10013' 'USR10014' 'USR10015'
 'USR10020' 'USR10022' 'USR10024' 'USR10027' 'USR10030' 'USR10031'
 'USR10043' 'USR10045' 'USR10046' 'USR10047' 'USR10048' 'USR10049'
 'USR10052' 'USR10054']

In [168]:
print("Transaction user ID range:")
print(
    transactions_clean["user_id_clean"]
    .dropna()
    .str.extract(r"(\d+)$")[0]
    .astype(float)
    .describe()
)

print("\nKYC user ID range:")
print(
    kyc_master["user_id_clean"]
    .dropna()
    .str.extract(r"(\d+)$")[0]
    .astype(float)
    .describe()
)

Transaction user ID range:
count    20000.000000
mean     54704.915200
std      26035.793944
min      10001.000000
25%      32038.250000
50%      54586.500000
75%      77394.250000
max      99998.000000
Name: 0, dtype: float64

KYC user ID range:
count    28920.000000
mean     54945.926694
std      26034.055461
min      10001.000000
25%      32518.250000
50%      54980.500000
75%      77424.500000
max      99999.000000
Name: 0, dtype: float64

In [169]:
def clean_user_id_core(x):
    if pd.isna(x):
        return pd.NA
    
    x = str(x).strip().upper()
    
    # Remove common formatting characters
    x = x.replace(" ", "").replace("-", "").replace("_", "")
    
    # Remove USR prefix if present
    if x.startswith("USR"):
        x = x[3:]
    
    # Keep only numeric user ID
    if x.isdigit():
        return x
    
    return pd.NA

In [170]:
transactions_clean["user_id_core"] = (
    transactions_clean["user_id"].apply(clean_user_id_core)
)

kyc_master["user_id_core"] = (
    kyc_master["user_id"].apply(clean_user_id_core)
)

In [171]:
matched_users = transactions_clean["user_id_core"].isin(
    kyc_master["user_id_core"]
)

print("Transactions:", len(transactions_clean))
print("Transactions with matching KYC:", matched_users.sum())
print("Transactions without matching KYC:", (~matched_users).sum())

Transactions: 20000
Transactions with matching KYC: 6478
Transactions without matching KYC: 13522

In [172]:
unmatched = transactions_clean[
    ~transactions_clean["user_id_core"].isin(
        kyc_master["user_id_core"]
    )
]

print("Sample unmatched transaction users:")
print(
    unmatched[
        ["user_id", "user_id_clean", "user_id_core"]
    ].head(30)
)

Sample unmatched transaction users:
     user_id user_id_clean user_id_core
0   USR45826      USR45826        45826
2   USR87810      USR87810        87810
3   USR54287      USR54287        54287
4   USR53865      USR53865        53865
7   USR16629      USR16629        16629
9   USR51755      USR51755        51755
10  USR81003      USR81003        81003
12  USR37834      USR37834        37834
13  USR78386      USR78386        78386
14  USR21114      USR21114        21114
15  USR96222      USR96222        96222
16  USR13976      USR13976        13976
17  USR55935      USR55935        55935
18  USR13890      USR13890        13890
19  USR15778      USR15778        15778
20  USR15834      USR15834        15834
21  USR33189      USR33189        33189
23  USR99474      USR99474        99474
25  USR85411      USR85411        85411
27  USR54536      USR54536        54536
28  USR93890      USR93890        93890
31  USR31880      USR31880        31880
32  USR95466      USR95466        95466
35  USR68024      USR68024        68024
38  USR87162      USR87162        87162
39  USR81720      USR81720        81720
40  USR76098      USR76098        76098
45  USR30273      USR30273        30273
46  USR84134      USR84134        84134
47  USR91737      USR91737        91737

In [173]:
print("Sample KYC user IDs:")
print(
    kyc_master[
        ["user_id", "user_id_clean", "user_id_core"]
    ].head(30)
)

Sample KYC user IDs:
         user_id user_id_clean user_id_core
7461    usr10001      USR10001        10001
26479   USR10007      USR10007        10007
12457   USR10010      USR10010        10010
32312   USR10013      USR10013        10013
6867   USR-10014      USR10014        10014
8890    USR10015      USR10015        10015
17832   USR10020      USR10020        10020
33788   usr10022      USR10022        10022
19070  USR-10024      USR10024        10024
29650  USR 10027      USR10027        10027
11903   USR10030      USR10030        10030
21220  usr_10031      USR10031        10031
4636    USR10043      USR10043        10043
2508   usr_10045      USR10045        10045
9482   usr_10046      USR10046        10046
16492   USR10047      USR10047        10047
27435   USR10048      USR10048        10048
36213   usr10049      USR10049        10049
8683    USR10052      USR10052        10052
14427   usr10054      USR10054        10054
9281    USR10057      USR10057        10057
18331   USR10059      USR10059        10059
12165   USR10064      USR10064        10064
33535   USR10066      USR10066        10066
17951  USR 10069      USR10069        10069
735     USR10070      USR10070        10070
15891   USR10078      USR10078        10078
28340   USR10085      USR10085        10085
34293   USR10086      USR10086        10086
14299   usr10088      USR10088        10088

In [174]:
print("KYC unique users:",
      kyc_master["user_id_core"].nunique())

print("Transaction unique users:",
      transactions_clean["user_id_core"].nunique())

common_users = (
    transactions_clean["user_id_core"]
    .dropna()
    .isin(kyc_master["user_id_core"])
)

print("Transaction users found in KYC:",
      common_users.sum())

KYC unique users: 28920
Transaction unique users: 17878
Transaction users found in KYC: 6478

In [175]:
transactions_clean["kyc_match_flag"] = transactions_clean["user_id_core"].isin(
    kyc_master["user_id_core"]
).astype(int)

In [176]:
total_txn = len(transactions_clean)
matched_txn = transactions_clean["kyc_match_flag"].sum()
unmatched_txn = total_txn - matched_txn

unique_txn_users = transactions_clean["user_id_core"].nunique()
unique_txn_users_with_kyc = transactions_clean.loc[
    transactions_clean["kyc_match_flag"] == 1, "user_id_core"
].nunique()

print("Total transactions:", total_txn)
print("Transactions with matching KYC:", matched_txn)
print("Transactions without matching KYC:", unmatched_txn)
print("Percentage with KYC:", round(matched_txn / total_txn * 100, 2))
print("Percentage without KYC:", round(unmatched_txn / total_txn * 100, 2))
print("Unique transaction users:", unique_txn_users)
print("Unique transaction users with KYC:", unique_txn_users_with_kyc)

Total transactions: 20000
Transactions with matching KYC: 6478
Transactions without matching KYC: 13522
Percentage with KYC: 32.39
Percentage without KYC: 67.61
Unique transaction users: 17878
Unique transaction users with KYC: 5799

## PHASE 2 — MERCHANT DATA CLEANING AND VALIDATION

In [177]:
print("Merchant rows:", len(merchants))
print("Exact duplicate rows:", merchants.duplicated().sum())
print("Duplicate merchant_id_clean (raw records):", merchants["merchant_id_clean"].duplicated(keep=False).sum())

Merchant rows: 6210
Exact duplicate rows: 12
Duplicate merchant_id_clean (raw records): 3048

In [178]:
merchants_clean = merchants.drop_duplicates().copy()

print("Rows before:", len(merchants))
print("Rows after exact duplicate removal:", len(merchants_clean))

Rows before: 6210
Rows after exact duplicate removal: 6198

In [179]:
merchant_id_counts = merchants_clean["merchant_id_clean"].value_counts()

print(merchant_id_counts.value_counts().sort_index())
print("Merchant IDs with more than 1 record:", (merchant_id_counts > 1).sum())

count
1    3167
2     997
3     247
4      52
5      14
6       3
Name: count, dtype: int64
Merchant IDs with more than 1 record: 1313

In [180]:
def clean_business_type(x):
    if pd.isna(x):
        return "UNKNOWN"

    x = str(x).strip().upper().replace("-", "_").replace(" ", "_")

    if x == "INDIVIDUAL":
        return "Individual"

    elif x == "PARTNERSHIP":
        return "Partnership"

    elif x == "SOLE_PROPRIETOR":
        return "Sole Proprietor"

    elif x == "PRIVATE_LIMITED":
        return "Private Limited"

    else:
        return "UNKNOWN"

In [181]:
merchants_clean["business_type_clean"] = (
    merchants_clean["business_type"].apply(clean_business_type)
)

merchants_clean["business_type_clean"].value_counts(dropna=False)

business_type_clean
Individual         1592
Sole Proprietor    1553
Private Limited    1543
Partnership        1510
Name: count, dtype: int64

In [182]:
merchants_clean["merchant_category_clean"] = (
    merchants_clean["mcc_clean"]
    .map(mcc_category_map)
    .fillna("Unknown")
)

merchants_clean["merchant_category_clean"].value_counts(dropna=False)

merchant_category_clean
Unknown                 692
Transportation          586
Department Stores       580
Clothing                569
Hotels & Hospitality    557
Telecom                 557
Food & Restaurants      547
Pharmacy & Medical      547
Grocery                 528
Other Retail            522
Books & Stationery      513
Name: count, dtype: int64

In [183]:
def clean_onboarding_date(x):
    if pd.isna(x):
        return pd.NaT

    x = str(x).strip()

    if x.isdigit() and len(x) >= 9:
        return pd.to_datetime(
            int(x),
            unit="s",
            errors="coerce"
        )

    formats = [
        "%Y-%m-%d %H:%M:%S",
        "%Y-%m-%d",
        "%Y/%m/%d",
        "%d/%m/%Y %I:%M %p",
        "%d/%m/%Y",
        "%m-%d-%Y",
        "%d-%m-%Y",
        "%d-%b-%Y",
        "%d-%B-%Y",
    ]

    for fmt in formats:
        try:
            return pd.to_datetime(x, format=fmt)
        except:
            pass

    return pd.NaT

In [184]:
merchants_clean["onboarding_date_clean"] = (
    merchants_clean["onboarding_date"].apply(clean_onboarding_date)
)

print("Missing before:", merchants_clean["onboarding_date"].isna().sum())
print("Missing after cleaning:", merchants_clean["onboarding_date_clean"].isna().sum())

Missing before: 499
Missing after cleaning: 499

In [185]:
today = pd.Timestamp("2026-09-15")

merchants_clean["missing_onboarding_date_flag"] = (
    merchants_clean["onboarding_date_clean"].isna()
).astype(int)

merchants_clean["invalid_onboarding_date_flag"] = (
    merchants_clean["onboarding_date_clean"].notna()
    & (
        (merchants_clean["onboarding_date_clean"] > today)
        | (merchants_clean["onboarding_date_clean"] < pd.Timestamp("2015-01-01"))
    )
).astype(int)

print("Missing onboarding date:", merchants_clean["missing_onboarding_date_flag"].sum())
print("Invalid onboarding date:", merchants_clean["invalid_onboarding_date_flag"].sum())

Missing onboarding date: 499
Invalid onboarding date: 0

In [186]:
def clean_settlement_account(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).strip().upper()
    x = x.replace(" ", "")

    return x

In [187]:
merchants_clean["settlement_account_clean"] = (
    merchants_clean["settlement_account"].apply(clean_settlement_account)
)

merchants_clean["missing_settlement_account_flag"] = (
    merchants_clean["settlement_account_clean"].isna()
).astype(int)

merchants_clean["masked_settlement_account_flag"] = (
    merchants_clean["settlement_account_clean"]
    .fillna("")
    .str.contains("X", regex=False)
).astype(int)

print("Missing settlement account:", merchants_clean["missing_settlement_account_flag"].sum())
print("Masked settlement account:", merchants_clean["masked_settlement_account_flag"].sum())

Missing settlement account: 2445
Masked settlement account: 1459

In [188]:
merchants_clean["declared_avg_ticket_clean"] = (
    merchants_clean["declared_avg_ticket_size"].apply(clean_amount)
)

merchants_clean["missing_avg_ticket_flag"] = (
    merchants_clean["declared_avg_ticket_clean"].isna()
).astype(int)

merchants_clean["negative_avg_ticket_flag"] = (
    merchants_clean["declared_avg_ticket_clean"] < 0
).astype(int)

print("Missing declared avg ticket:", merchants_clean["missing_avg_ticket_flag"].sum())
print("Negative declared avg ticket:", merchants_clean["negative_avg_ticket_flag"].sum())

Missing declared avg ticket: 371
Negative declared avg ticket: 501

In [189]:
def clean_merchant_id_core(x):
    if pd.isna(x):
        return pd.NA

    x = str(x).strip().upper()
    x = x.replace(" ", "").replace("-", "").replace("_", "")

    if x.startswith("MCH"):
        x = x[3:]

    if x.isdigit():
        return x

    return pd.NA

In [190]:
merchants_clean["merchant_id_core"] = (
    merchants_clean["merchant_id"].apply(clean_merchant_id_core)
)

transactions_clean["merchant_id_core"] = (
    transactions_clean["merchant_id"].apply(clean_merchant_id_core)
)

print("Merchant core ID range:")
print(merchants_clean["merchant_id_core"].dropna().astype(int).describe())

print("\nTransaction merchant core ID range:")
print(transactions_clean["merchant_id_core"].dropna().astype(int).describe())

Merchant core ID range:
count    6198.000000
mean     5528.916102
std      2610.983552
min      1001.000000
25%      3277.500000
50%      5562.500000
75%      7826.250000
max      9999.000000
Name: merchant_id_core, dtype: float64

Transaction merchant core ID range:
count    20000.000000
mean      5519.628150
std       2602.620137
min       1000.000000
25%       3253.000000
50%       5550.000000
75%       7785.000000
max       9999.000000
Name: merchant_id_core, dtype: float64

In [191]:
matched_merchant_core = transactions_clean["merchant_id_core"].isin(
    merchants_clean["merchant_id_core"]
)

print("Transactions:", len(transactions_clean))
print("Transactions with matching merchant (merchant_id_clean):",
      transactions_clean["merchant_id_clean"].isin(merchants_clean["merchant_id_clean"]).sum())
print("Transactions with matching merchant (merchant_id_core):",
      matched_merchant_core.sum())

Transactions: 20000
Transactions with matching merchant (merchant_id_clean): 9275
Transactions with matching merchant (merchant_id_core): 9631

In [192]:
merchant_conflict_check = merchants_clean[
    merchants_clean["merchant_id_core"].duplicated(keep=False)
].sort_values("merchant_id_core")

display(
    merchant_conflict_check[[
        "merchant_id", "merchant_id_core", "merchant_name",
        "merchant_category_clean", "business_type_clean",
        "onboarding_date_clean", "merchant_status"
    ]].head(30)
)

     merchant_id merchant_id_core  ... onboarding_date_clean merchant_status
970      MCH1007             1007  ...   2023-11-19 00:00:00         Enabled
3150     MCH1007             1007  ...   2025-06-30 00:00:00        Disabled
1677     MCH1011             1011  ...   2023-11-02 00:00:00          Active
2679     MCH1011             1011  ...   2023-11-02 00:00:00       Suspended
4712    MCH 1014             1014  ...   2023-12-21 00:00:00            Live
448      MCH1014             1014  ...   2024-03-23 00:00:00          ACTIVE
5659    MCH 1016             1016  ...                   NaT               A
4912     MCH1016             1016  ...   2025-02-08 00:00:00               S
1031     MCH1016             1016  ...   2023-03-10 00:00:00          ACTIVE
4289     MCH1021             1021  ...                   NaT          ACTIVE
4454     MCH1021             1021  ...   2025-11-16 17:48:36         Enabled
3093    MCH 1032             1032  ...   2025-09-21 00:00:00         Enabled
4567     mch1032             1032  ...   2025-04-20 00:00:00          Active
5949     mch1032             1032  ...   2025-04-20 00:00:00        Inactive
3620    MCH-1033             1033  ...   2023-09-11 00:00:00          Active
6070     MCH1033             1033  ...   2023-07-08 00:00:00          Closed
1395        1039             1039  ...   2023-07-14 00:00:00          Active
4600     mch1039             1039  ...   2025-07-28 00:43:00          Active
5312    MCH-1040             1040  ...   2023-01-06 00:00:00            Live
4975     MCH1040             1040  ...   2024-09-08 00:00:00               A
3452     MCH1047             1047  ...   2023-08-01 00:00:00          Active
2849     MCH1047             1047  ...   2023-08-20 01:01:00         Enabled
1195     MCH1060             1060  ...   2023-05-18 00:00:00          Closed
4554     MCH1060             1060  ...   2023-07-27 03:57:00         Enabled
149      mch1060             1060  ...   2024-05-02 09:00:14         Enabled
5201     mch1064             1064  ...   2025-03-12 00:00:00            Live
2890        1064             1064  ...   2025-09-09 22:49:04          ACTIVE
3639    MCH 1071             1071  ...   2024-06-23 13:38:43          Active
4719     MCH1071             1071  ...   2025-01-21 00:00:00               A
4668     MCH1071             1071  ...   2025-04-17 00:00:00         Enabled

[30 rows x 7 columns]

In [193]:
category_n = merchants_clean.groupby("merchant_id_core")["merchant_category_clean"].transform("nunique")
business_type_n = merchants_clean.groupby("merchant_id_core")["business_type_clean"].transform("nunique")
status_n = merchants_clean.groupby("merchant_id_core")["merchant_status"].transform("nunique")

merchants_clean["merchant_category_conflict_flag"] = (category_n > 1).astype(int)
merchants_clean["merchant_business_type_conflict_flag"] = (business_type_n > 1).astype(int)
merchants_clean["merchant_status_conflict_flag"] = (status_n > 1).astype(int)

merchants_clean["merchant_conflict_score"] = (
    merchants_clean["merchant_category_conflict_flag"]
    + merchants_clean["merchant_business_type_conflict_flag"]
    + merchants_clean["merchant_status_conflict_flag"]
)

merchants_clean["merchant_conflict_score"].value_counts().sort_index()

merchant_conflict_score
0    2996
1     240
2     839
3    2123
Name: count, dtype: int64

In [194]:
merchant_master = merchants_clean.dropna(subset=["merchant_id_core"]).copy()

merchant_master["merchant_record_count"] = (
    merchant_master.groupby("merchant_id_core")["merchant_id_core"]
    .transform("size")
)

merchant_master = merchant_master.sort_values(
    ["merchant_id_core", "onboarding_date_clean"]
)

merchant_master = (
    merchant_master
    .drop_duplicates("merchant_id_core", keep="last")
    .copy()
)

print("Merchant history rows:", len(merchants_clean))
print("Merchant rows dropped for unparseable merchant_id:",
      merchants_clean["merchant_id_core"].isna().sum())
print("Merchant master rows:", len(merchant_master))
print("Unique merchants:", merchant_master["merchant_id_core"].nunique())

Merchant history rows: 6198
Merchant rows dropped for unparseable merchant_id: 0
Merchant master rows: 4343
Unique merchants: 4343

In [195]:
matched_merchant_txn = transactions_clean["merchant_id_core"].isin(
    merchant_master["merchant_id_core"]
)

print("Total transactions:", len(transactions_clean))
print("Transactions with matching merchant:", matched_merchant_txn.sum())
print("Transactions without matching merchant:", (~matched_merchant_txn).sum())
print("Percentage with merchant match:", round(matched_merchant_txn.mean() * 100, 2))

transactions_clean["merchant_match_flag"] = matched_merchant_txn.astype(int)

Total transactions: 20000
Transactions with matching merchant: 9631
Transactions without matching merchant: 10369
Percentage with merchant match: 48.16

# FraudLens AI — Remaining Project

We are continuing from the completed transaction, KYC and merchant cleaning work. The next stages build the chargeback layer, final analytical dataset, business analytics, explainable risk scores, fraud-ring detection and final exports used by the Streamlit application.

In [196]:
import json
import numpy as np
import pandas as pd
import networkx as nx
from pathlib import Path

## 1. Load and inspect chargebacks

Chargebacks are important because they provide observed dispute evidence. We will keep repeated transaction IDs because one transaction can have multiple complaint records.

In [197]:
chargebacks_raw = pd.DataFrame(json.load(open(BASE_DIR / "track1_chargebacks.json")))
print("Chargeback rows:", len(chargebacks_raw))
print("Columns:", chargebacks_raw.columns.tolist())

Chargeback rows: 2884
Columns: ['complaint_id', 'txn_id', 'user_id', 'merchant_id', 'transaction_timestamp', 'reported_timestamp', 'disputed_amount', 'reason_code', 'complaint_text', 'resolution_status', 'bank_response_timestamp', 'severity', 'channel']

In [198]:
chargebacks = chargebacks_raw.drop_duplicates().copy()

print("Rows after exact duplicate removal:", len(chargebacks))
print("Duplicate complaint IDs:", chargebacks["complaint_id"].duplicated().sum())
print("Repeated transaction IDs:", chargebacks["txn_id"].duplicated().sum())

Rows after exact duplicate removal: 2800
Duplicate complaint IDs: 0
Repeated transaction IDs: 218

## 2. Clean chargeback identifiers

In [199]:
chargebacks["txn_id_clean"] = chargebacks["txn_id"].apply(clean_txn_id)
chargebacks["user_id_core"] = chargebacks["user_id"].apply(clean_user_id_core)
chargebacks["merchant_id_core"] = chargebacks["merchant_id"].apply(clean_merchant_id_core)
chargebacks["complaint_id_clean"] = chargebacks["complaint_id"].astype("string").str.strip().str.upper()

## 3. Clean chargeback amounts

In [200]:
chargebacks["disputed_amount_clean"] = chargebacks["disputed_amount"].apply(clean_amount)
chargebacks["negative_disputed_amount_flag"] = (chargebacks["disputed_amount_clean"] < 0).astype(int)
chargebacks["disputed_amount_calc"] = chargebacks["disputed_amount_clean"].where(chargebacks["disputed_amount_clean"] >= 0)

print("Missing disputed amount:", chargebacks["disputed_amount_clean"].isna().sum())
print("Negative disputed amount:", chargebacks["negative_disputed_amount_flag"].sum())

Missing disputed amount:

 179
Negative disputed amount: 220

## 4. Clean chargeback timestamps

In [201]:
chargebacks["transaction_timestamp_clean"] = chargebacks["transaction_timestamp"].apply(clean_timestamp)
chargebacks["reported_timestamp_clean"] = chargebacks["reported_timestamp"].apply(clean_timestamp)
chargebacks["bank_response_timestamp_clean"] = chargebacks["bank_response_timestamp"].apply(clean_timestamp)

chargebacks["reporting_delay_days"] = (
    chargebacks["reported_timestamp_clean"] - chargebacks["transaction_timestamp_clean"]
).dt.total_seconds() / 86400

chargebacks["invalid_reporting_delay_flag"] = (
    chargebacks["reporting_delay_days"] < 0
).astype(int)
chargebacks["delayed_dispute_7d_flag"] = (
    chargebacks["reporting_delay_days"] > 7
).astype(int)

print("Missing transaction timestamps:", chargebacks["transaction_timestamp_clean"].isna().sum())
print("Missing reported timestamps:", chargebacks["reported_timestamp_clean"].isna().sum())
print("Disputes after 7 days:", chargebacks["delayed_dispute_7d_flag"].sum())

Missing transaction timestamps: 1881
Missing reported timestamps: 1848
Disputes after 7 days: 78

## 5. Normalize chargeback categories

In [202]:
chargebacks["reason_code_clean"] = (
    chargebacks["reason_code"]
    .astype("string")
    .str.strip()
    .str.upper()
)

chargebacks["resolution_status_clean"] = (
    chargebacks["resolution_status"]
    .astype("string")
    .str.strip()
    .str.upper()
)

severity_map = {
    "L": "LOW",
    "LOW": "LOW",
    "M": "MEDIUM",
    "MEDIUM": "MEDIUM",
    "H": "HIGH",
    "HIGH": "HIGH",
    "C": "CRITICAL",
    "CRITICAL": "CRITICAL"
}

chargebacks["severity_clean"] = (
    chargebacks["severity"]
    .astype("string")
    .str.strip()
    .str.upper()
    .map(severity_map)
    .fillna("UNKNOWN")
)

chargebacks["channel_clean"] = (
    chargebacks["channel"]
    .astype("string")
    .str.strip()
    .str.upper()
)

print(chargebacks["severity_clean"].value_counts(dropna=False))

severity_clean
UNKNOWN     791
MEDIUM      757
LOW         719
HIGH        443
CRITICAL     90
Name: count, dtype: int64

## 6. Validate chargeback foreign keys

In [203]:
chargebacks["txn_match_flag"] = chargebacks["txn_id_clean"].isin(transactions_clean["txn_id_clean"]).astype(int)
chargebacks["user_match_flag"] = chargebacks["user_id_core"].isin(kyc_master["user_id_core"]).astype(int)
chargebacks["merchant_match_flag"] = chargebacks["merchant_id_core"].isin(merchant_master["merchant_id_core"]).astype(int)

print("Transaction matches:", chargebacks["txn_match_flag"].sum())
print("User matches:", chargebacks["user_match_flag"].sum())
print("Merchant matches:", chargebacks["merchant_match_flag"].sum())

Transaction matches: 2607
User matches: 885
Merchant matches: 1299

## 7. Build chargeback aggregates

The transaction table must remain one row per transaction. We aggregate multiple complaints before joining them so transaction counts and amounts are not inflated.

In [204]:
chargeback_txn = (
    chargebacks
    .groupby("txn_id_clean", dropna=False)
    .agg(
        chargeback_count=("complaint_id_clean", "nunique"),
        disputed_amount=("disputed_amount_calc", "sum"),
        max_severity=("severity_clean", lambda x: ", ".join(sorted(set(x)))),
        delayed_dispute_count=("delayed_dispute_7d_flag", "sum"),
        reporting_delay_days=("reporting_delay_days", "mean")
    )
    .reset_index()
)

chargeback_txn["has_chargeback_flag"] = (chargeback_txn["chargeback_count"] > 0).astype(int)
chargeback_txn["disputed_amount"] = chargeback_txn["disputed_amount"].fillna(0)

print("Chargeback transaction aggregates:", len(chargeback_txn))

Chargeback transaction aggregates: 2568

## 8. Final transaction analytical dataset

In [205]:
analytics_transactions = transactions_clean.copy()

kyc_join = kyc_master.drop_duplicates("user_id_core").copy()
merchant_join = merchant_master.drop_duplicates("merchant_id_core").copy()

kyc_cols = [
    "user_id_core", "kyc_status_clean", "risk_segment_clean",
    "monthly_income_clean", "missing_pan_flag", "missing_aadhaar_flag",
    "missing_dob_flag", "identity_conflict_score"
]

merchant_cols = [
    "merchant_id_core", "merchant_name", "merchant_category_clean",
    "business_type_clean", "merchant_status", "onboarding_date_clean",
    "declared_avg_ticket_clean", "merchant_conflict_score"
]

analytics_transactions = analytics_transactions.merge(
    kyc_join[kyc_cols], on="user_id_core", how="left", validate="many_to_one"
)

analytics_transactions = analytics_transactions.merge(
    merchant_join[merchant_cols], on="merchant_id_core", how="left", validate="many_to_one"
)

analytics_transactions = analytics_transactions.merge(
    chargeback_txn, on="txn_id_clean", how="left", validate="one_to_one"
)

analytics_transactions["chargeback_count"] = analytics_transactions["chargeback_count"].fillna(0)
analytics_transactions["disputed_amount"] = analytics_transactions["disputed_amount"].fillna(0)
analytics_transactions["has_chargeback_flag"] = analytics_transactions["has_chargeback_flag"].fillna(0).astype(int)
analytics_transactions["delayed_dispute_count"] = analytics_transactions["delayed_dispute_count"].fillna(0)

print("Transaction rows before joins:", len(transactions_clean))
print("Analytics transaction rows:", len(analytics_transactions))
print("Duplicate transaction IDs:", analytics_transactions["txn_id_clean"].duplicated().sum())

Transaction rows before joins: 20000
Analytics transaction rows: 20000
Duplicate transaction IDs: 0

## 9. Add time and behavioral features

In [206]:
analytics_transactions["date"] = analytics_transactions["timestamp_clean"].dt.date
analytics_transactions["hour"] = analytics_transactions["timestamp_clean"].dt.hour
analytics_transactions["day_of_week"] = analytics_transactions["timestamp_clean"].dt.day_name()
analytics_transactions["is_weekend"] = (analytics_transactions["timestamp_clean"].dt.dayofweek >= 5).astype(int)

user_stats = analytics_transactions.groupby("user_id_core")["amount_clean"].agg(
    user_txn_count="count",
    user_avg_amount="mean",
    user_total_amount="sum",
    user_std_amount="std"
).reset_index()

merchant_stats = analytics_transactions.groupby("merchant_id_core")["amount_clean"].agg(
    merchant_txn_count="count",
    merchant_avg_amount="mean",
    merchant_total_amount="sum",
    merchant_std_amount="std"
).reset_index()

analytics_transactions = analytics_transactions.merge(user_stats, on="user_id_core", how="left")
analytics_transactions = analytics_transactions.merge(merchant_stats, on="merchant_id_core", how="left")

analytics_transactions["user_amount_deviation"] = (
    analytics_transactions["amount_clean"] - analytics_transactions["user_avg_amount"]
) / analytics_transactions["user_std_amount"].replace(0, np.nan)

analytics_transactions["merchant_amount_deviation"] = (
    analytics_transactions["amount_clean"] - analytics_transactions["merchant_avg_amount"]
) / analytics_transactions["merchant_std_amount"].replace(0, np.nan)

analytics_transactions["large_user_deviation_flag"] = (
    analytics_transactions["user_amount_deviation"].abs() >= 3
).fillna(False).astype(int)

analytics_transactions["large_merchant_deviation_flag"] = (
    analytics_transactions["merchant_amount_deviation"].abs() >= 3
).fillna(False).astype(int)

## 10. User-level analytics and risk features

In [207]:
user_risk = (
    analytics_transactions
    .groupby("user_id_core")
    .agg(
        transaction_count=("txn_id_clean", "nunique"),
        total_amount=("amount_clean", "sum"),
        average_amount=("amount_clean", "mean"),
        failed_count=("status_clean", lambda x: (x == "FAILED").sum()),
        pending_count=("status_clean", lambda x: (x == "PENDING").sum()),
        unique_merchants=("merchant_id_core", "nunique"),
        chargeback_count=("chargeback_count", "sum"),
        disputed_amount=("disputed_amount", "sum"),
        missing_utr_count=("missing_utr_flag", "sum"),
        negative_amount_count=("negative_amount_flag", "sum"),
        anomalous_amount_count=("large_user_deviation_flag", "sum")
    )
    .reset_index()
)

user_risk["failed_rate"] = user_risk["failed_count"] / user_risk["transaction_count"].replace(0, np.nan)
user_risk["chargeback_ratio"] = user_risk["chargeback_count"] / user_risk["transaction_count"].replace(0, np.nan)

user_profile = kyc_join[[
    "user_id_core", "kyc_status_clean", "risk_segment_clean",
    "missing_pan_flag", "missing_aadhaar_flag", "missing_dob_flag",
    "identity_conflict_score"
]].copy()

user_risk = user_risk.merge(user_profile, on="user_id_core", how="left")

user_risk["risk_score"] = 0.0
user_risk["risk_score"] += user_risk["chargeback_ratio"].fillna(0).clip(0, 1) * 30
user_risk["risk_score"] += user_risk["failed_rate"].fillna(0).clip(0, 1) * 15
user_risk["risk_score"] += (user_risk["identity_conflict_score"].fillna(0).clip(0, 4) / 4) * 20
user_risk["risk_score"] += user_risk["missing_utr_count"].gt(0).astype(int) * 5
user_risk["risk_score"] += user_risk["negative_amount_count"].gt(0).astype(int) * 5
user_risk["risk_score"] += user_risk["anomalous_amount_count"].gt(0).astype(int) * 10
user_risk["risk_score"] += user_risk["kyc_status_clean"].isin(["REJECTED", "PENDING"]).astype(int) * 10
user_risk["risk_score"] += user_risk["risk_segment_clean"].eq("HIGH").astype(int) * 5
user_risk["risk_score"] = user_risk["risk_score"].clip(0, 100).round(2)

user_risk["risk_level"] = pd.cut(
    user_risk["risk_score"],
    bins=[-1, 24.99, 49.99, 74.99, 100],
    labels=["LOW", "MEDIUM", "HIGH", "CRITICAL"]
).astype(str)

## 11. Merchant-level analytics and risk features

In [208]:
merchant_risk = (
    analytics_transactions
    .groupby("merchant_id_core")
    .agg(
        transaction_count=("txn_id_clean", "nunique"),
        total_amount=("amount_clean", "sum"),
        average_amount=("amount_clean", "mean"),
        unique_users=("user_id_core", "nunique"),
        failed_count=("status_clean", lambda x: (x == "FAILED").sum()),
        chargeback_count=("chargeback_count", "sum"),
        disputed_amount=("disputed_amount", "sum"),
        delayed_dispute_count=("delayed_dispute_count", "sum"),
        anomalous_amount_count=("large_merchant_deviation_flag", "sum")
    )
    .reset_index()
)

merchant_risk["failed_rate"] = merchant_risk["failed_count"] / merchant_risk["transaction_count"].replace(0, np.nan)
merchant_risk["chargeback_ratio"] = merchant_risk["chargeback_count"] / merchant_risk["transaction_count"].replace(0, np.nan)

merchant_profile = merchant_join[[
    "merchant_id_core", "merchant_name", "merchant_category_clean",
    "business_type_clean", "merchant_status", "merchant_conflict_score"
]].copy()

merchant_risk = merchant_risk.merge(merchant_profile, on="merchant_id_core", how="left")

merchant_risk["risk_score"] = 0.0
merchant_risk["risk_score"] += merchant_risk["chargeback_ratio"].fillna(0).clip(0, 1) * 45
merchant_risk["risk_score"] += merchant_risk["failed_rate"].fillna(0).clip(0, 1) * 15
merchant_risk["risk_score"] += merchant_risk["delayed_dispute_count"].gt(0).astype(int) * 10
merchant_risk["risk_score"] += merchant_risk["anomalous_amount_count"].gt(0).astype(int) * 15
merchant_risk["risk_score"] += (merchant_risk["merchant_conflict_score"].fillna(0).clip(0, 3) / 3) * 15
merchant_risk["risk_score"] = merchant_risk["risk_score"].clip(0, 100).round(2)

merchant_risk["risk_level"] = pd.cut(
    merchant_risk["risk_score"],
    bins=[-1, 24.99, 49.99, 74.99, 100],
    labels=["LOW", "MEDIUM", "HIGH", "CRITICAL"]
).astype(str)

## 12. Transaction-level risk score

In [209]:
analytics_transactions = analytics_transactions.merge(
    user_risk[["user_id_core", "risk_score", "risk_level"]].rename(
        columns={"risk_score": "user_risk_score", "risk_level": "user_risk_level"}
    ),
    on="user_id_core", how="left", validate="many_to_one"
)

analytics_transactions = analytics_transactions.merge(
    merchant_risk[["merchant_id_core", "risk_score", "risk_level"]].rename(
        columns={"risk_score": "merchant_risk_score", "risk_level": "merchant_risk_level"}
    ),
    on="merchant_id_core", how="left", validate="many_to_one"
)

analytics_transactions["transaction_risk_score"] = 0.0
analytics_transactions["transaction_risk_score"] += analytics_transactions["user_risk_score"].fillna(0) * 0.30
analytics_transactions["transaction_risk_score"] += analytics_transactions["merchant_risk_score"].fillna(0) * 0.30
analytics_transactions["transaction_risk_score"] += analytics_transactions["large_user_deviation_flag"] * 15
analytics_transactions["transaction_risk_score"] += analytics_transactions["large_merchant_deviation_flag"] * 10
analytics_transactions["transaction_risk_score"] += analytics_transactions["missing_utr_flag"] * 5
analytics_transactions["transaction_risk_score"] += analytics_transactions["negative_amount_flag"] * 10
analytics_transactions["transaction_risk_score"] += analytics_transactions["has_chargeback_flag"] * 20
analytics_transactions["transaction_risk_score"] = analytics_transactions["transaction_risk_score"].clip(0, 100).round(2)

analytics_transactions["transaction_risk_level"] = pd.cut(
    analytics_transactions["transaction_risk_score"],
    bins=[-1, 24.99, 49.99, 74.99, 100],
    labels=["LOW", "MEDIUM", "HIGH", "CRITICAL"]
).astype(str)

## 13. Risk explanations

In [210]:
def user_reason(row):
    reasons = []
    if row["chargeback_ratio"] >= 0.1:
        reasons.append("elevated chargeback ratio")
    if row["failed_rate"] >= 0.2:
        reasons.append("high failed transaction rate")
    if row["identity_conflict_score"] >= 2:
        reasons.append("identity conflicts in KYC history")
    if row["kyc_status_clean"] in ["REJECTED", "PENDING"]:
        reasons.append("KYC is not fully approved")
    if row["risk_segment_clean"] == "HIGH":
        reasons.append("high KYC risk segment")
    if row["anomalous_amount_count"] > 0:
        reasons.append("unusual transaction amounts")
    if row["missing_utr_count"] > 0:
        reasons.append("transactions with missing UTR")
    return "; ".join(reasons) if reasons else "No major risk signal"

user_risk["risk_reasons"] = user_risk.apply(user_reason, axis=1)

def merchant_reason(row):
    reasons = []
    if row["chargeback_ratio"] >= 0.1:
        reasons.append("elevated chargeback ratio")
    if row["failed_rate"] >= 0.2:
        reasons.append("high failed transaction rate")
    if row["delayed_dispute_count"] > 0:
        reasons.append("delayed disputes")
    if row["anomalous_amount_count"] > 0:
        reasons.append("unusual transaction amounts")
    if row["merchant_conflict_score"] > 0:
        reasons.append("merchant profile conflicts")
    return "; ".join(reasons) if reasons else "No major risk signal"

merchant_risk["risk_reasons"] = merchant_risk.apply(merchant_reason, axis=1)

## 14. Detect suspicious fraud rings

We use a bipartite user-merchant graph. To reduce noise, the graph focuses on users and merchants with elevated risk or chargeback activity. Connected components are then scored using actual transaction and dispute evidence.

In [211]:
graph = nx.Graph()

high_users = set(user_risk.loc[user_risk["risk_score"] >= 50, "user_id_core"].dropna())
high_merchants = set(merchant_risk.loc[merchant_risk["risk_score"] >= 50, "merchant_id_core"].dropna())

suspicious_edges = analytics_transactions[
    analytics_transactions["user_id_core"].notna()
    & analytics_transactions["merchant_id_core"].notna()
    & (
        analytics_transactions["user_id_core"].isin(high_users)
        | analytics_transactions["merchant_id_core"].isin(high_merchants)
        | (analytics_transactions["has_chargeback_flag"] == 1)
    )
].copy()

for _, row in suspicious_edges.iterrows():
    user_node = "U_" + str(row["user_id_core"])
    merchant_node = "M_" + str(row["merchant_id_core"])
    graph.add_edge(user_node, merchant_node)

components = list(nx.connected_components(graph))
print("Graph nodes:", graph.number_of_nodes())
print("Graph edges:", graph.number_of_edges())
print("Connected components:", len(components))

Graph nodes: 4607
Graph edges: 2483
Connected components: 2124

## 15. Score fraud rings

In [212]:
ring_rows = []
ring_members = []

for ring_number, component in enumerate(components, start=1):
    users = [x[2:] for x in component if x.startswith("U_")]
    merchants = [x[2:] for x in component if x.startswith("M_")]
    if len(users) < 2 or len(merchants) < 1:
        continue

    ring_txn = suspicious_edges[
        suspicious_edges["user_id_core"].isin(users)
        & suspicious_edges["merchant_id_core"].isin(merchants)
    ]

    total_amount = ring_txn["amount_clean"].sum()
    chargeback_amount = ring_txn["disputed_amount"].sum()
    chargeback_count = ring_txn["chargeback_count"].sum()
    risk_score = min(100, round(
        min(40, len(users) * 5)
        + min(25, len(merchants) * 8)
        + min(25, chargeback_count * 5)
        + min(10, chargeback_amount / max(total_amount, 1) * 100), 2
    ))

    reasons = []
    if len(users) >= 3:
        reasons.append("multiple connected users")
    if len(merchants) >= 2:
        reasons.append("multiple connected merchants")
    if chargeback_count > 0:
        reasons.append("linked chargeback activity")
    if chargeback_amount > 0 and total_amount > 0 and chargeback_amount / total_amount >= 0.05:
        reasons.append("elevated disputed amount ratio")

    ring_id = "RING_" + str(ring_number).zfill(4)
    ring_rows.append({
        "ring_id": ring_id,
        "user_count": len(users),
        "merchant_count": len(merchants),
        "transaction_count": len(ring_txn),
        "total_amount": total_amount,
        "chargeback_count": chargeback_count,
        "chargeback_amount": chargeback_amount,
        "risk_score": risk_score,
        "risk_level": "CRITICAL" if risk_score >= 75 else "HIGH" if risk_score >= 50 else "MEDIUM",
        "risk_reasons": "; ".join(reasons) if reasons else "connected high-risk activity"
    })

    for user in users:
        ring_members.append({"ring_id": ring_id, "member_type": "USER", "member_id": user})
    for merchant in merchants:
        ring_members.append({"ring_id": ring_id, "member_type": "MERCHANT", "member_id": merchant})

fraud_rings = pd.DataFrame(ring_rows).sort_values("risk_score", ascending=False).reset_index(drop=True)
ring_members = pd.DataFrame(ring_members)

print("Suspicious rings:", len(fraud_rings))
display(fraud_rings.head(10))

Suspicious rings: 289

     ring_id  ...                                       risk_reasons
0  RING_0694  ...  multiple connected users; linked chargeback ac...
1  RING_0270  ...  multiple connected merchants; linked chargebac...
2  RING_0535  ...  multiple connected merchants; linked chargebac...
3  RING_0265  ...  multiple connected users; linked chargeback ac...
4  RING_0131  ...  multiple connected users; linked chargeback ac...
5  RING_0330  ...  multiple connected merchants; linked chargebac...
6  RING_0304  ...  multiple connected merchants; linked chargebac...
7  RING_0648  ...  multiple connected merchants; linked chargebac...
8  RING_0581  ...  multiple connected merchants; linked chargebac...
9  RING_0872  ...  multiple connected merchants; linked chargebac...

[10 rows x 10 columns]

## 16. Business analytics

In [213]:
daily_metrics = (
    analytics_transactions
    .groupby("date")
    .agg(
        transaction_count=("txn_id_clean", "nunique"),
        transaction_amount=("amount_clean", "sum"),
        average_transaction_value=("amount_clean", "mean"),
        failed_count=("status_clean", lambda x: (x == "FAILED").sum()),
        pending_count=("status_clean", lambda x: (x == "PENDING").sum()),
        chargeback_count=("chargeback_count", "sum"),
        disputed_amount=("disputed_amount", "sum")
    )
    .reset_index()
)

daily_metrics["failed_rate"] = daily_metrics["failed_count"] / daily_metrics["transaction_count"].replace(0, np.nan)
daily_metrics["chargeback_ratio"] = daily_metrics["chargeback_count"] / daily_metrics["transaction_count"].replace(0, np.nan)

summary = pd.DataFrame({
    "metric": [
        "Total Transactions", "Total Transaction Amount", "Average Transaction Value",
        "Failed Rate", "Pending Rate", "Chargeback Count", "Disputed Amount",
        "High Risk Users", "High Risk Merchants", "High Risk Transactions",
        "Suspicious Rings", "Disputes After 7 Days"
    ],
    "value": [
        analytics_transactions["txn_id_clean"].nunique(),
        analytics_transactions["amount_clean"].sum(),
        analytics_transactions["amount_clean"].mean(),
        (analytics_transactions["status_clean"] == "FAILED").mean(),
        (analytics_transactions["status_clean"] == "PENDING").mean(),
        analytics_transactions["chargeback_count"].sum(),
        analytics_transactions["disputed_amount"].sum(),
        (user_risk["risk_level"].isin(["HIGH", "CRITICAL"])).sum(),
        (merchant_risk["risk_level"].isin(["HIGH", "CRITICAL"])).sum(),
        (analytics_transactions["transaction_risk_level"].isin(["HIGH", "CRITICAL"])).sum(),
        len(fraud_rings),
        chargebacks["delayed_dispute_7d_flag"].sum()
    ]
})

display(summary)

                       metric         value
0          Total Transactions  2.000000e+04
1    Total Transaction Amount  2.392326e+08
2   Average Transaction Value  1.196163e+04
3                 Failed Rate  9.775000e-02
4                Pending Rate  3.860000e-02
5            Chargeback Count  2.607000e+03
6             Disputed Amount  6.902430e+06
7             High Risk Users  1.250000e+02
8         High Risk Merchants  1.000000e+02
9      High Risk Transactions  5.700000e+01
10           Suspicious Rings  2.890000e+02
11      Disputes After 7 Days  7.800000e+01

## 17. Export the final FraudLens datasets

In [214]:
OUTPUT_DIR.mkdir(exist_ok=True)
analytics_transactions.to_csv(OUTPUT_DIR / "analytics_transactions.csv", index=False)
chargebacks.to_csv(OUTPUT_DIR / "chargebacks_clean.csv", index=False)
kyc_master.to_csv(OUTPUT_DIR / "kyc_master.csv", index=False)
merchant_master.to_csv(OUTPUT_DIR / "merchant_master.csv", index=False)
user_risk.to_csv(OUTPUT_DIR / "user_risk.csv", index=False)
merchant_risk.to_csv(OUTPUT_DIR / "merchant_risk.csv", index=False)
fraud_rings.to_csv(OUTPUT_DIR / "fraud_rings.csv", index=False)
ring_members.to_csv(OUTPUT_DIR / "ring_members.csv", index=False)
daily_metrics.to_csv(OUTPUT_DIR / "daily_metrics.csv", index=False)
summary.to_csv(OUTPUT_DIR / "summary.csv", index=False)
print("FraudLens outputs created:", OUTPUT_DIR.resolve())

FraudLens outputs created: /home/oai/Documents/datathon/fraudlens_output

## 18. Final validation

In [215]:
validation = {
    "analytics_rows_match": len(analytics_transactions) == len(transactions_clean),
    "duplicate_transaction_ids": int(analytics_transactions["txn_id_clean"].duplicated().sum()),
    "duplicate_kyc_users": int(kyc_master["user_id_core"].duplicated().sum()),
    "duplicate_merchant_ids": int(merchant_master["merchant_id_core"].duplicated().sum()),
    "duplicate_user_risk_users": int(user_risk["user_id_core"].duplicated().sum()),
    "duplicate_merchant_risk_ids": int(merchant_risk["merchant_id_core"].duplicated().sum())
}
print(validation)
assert validation["analytics_rows_match"]
assert validation["duplicate_transaction_ids"] == 0
assert validation["duplicate_kyc_users"] == 0
assert validation["duplicate_merchant_ids"] == 0
assert validation["duplicate_user_risk_users"] == 0
assert validation["duplicate_merchant_risk_ids"] == 0
print("FraudLens final validation PASSED")

{'analytics_rows_match': True, 'duplicate_transaction_ids': 0, 'duplicate_kyc_users': 0, 'duplicate_merchant_ids': 0, 'duplicate_user_risk_users': 0, 'duplicate_merchant_risk_ids': 0}
FraudLens final validation PASSED

## 19. Prepare the Streamlit project

The notebook remains the source of truth. These cells export the final datasets and create the Streamlit application from the same FraudLens outputs.

In [216]:
print("Streamlit project folder:")
print(PROJECT_DIR)
print("Output folder:")
print(OUTPUT_DIR)
print("Files ready:", sorted([p.name for p in OUTPUT_DIR.glob("*.csv")]))

Streamlit project folder:
/home/oai/Documents/datathon
Output folder:
/home/oai/Documents/datathon/fraudlens_output
Files ready: ['analytics_transactions.csv', 'chargebacks_clean.csv', 'daily_metrics.csv', 'fraud_rings.csv', 'kyc_master.csv', 'merchant_master.csv', 'merchant_risk.csv', 'ring_members.csv', 'summary.csv', 'user_risk.csv']

## 20. Create the Streamlit application

The following cell writes the application file. The app reads the exact CSV outputs produced by this notebook.

In [217]:
app_code = r'''import streamlit as st
import pandas as pd
import numpy as np
from pathlib import Path
import plotly.express as px

st.set_page_config(page_title="FraudLens AI", page_icon="🛡️", layout="wide")

BASE = Path(__file__).resolve().parent
DATA = BASE / "fraudlens_output"

@st.cache_data
def load_data():
    files = {
        "tx": "analytics_transactions.csv",
        "users": "user_risk.csv",
        "merchants": "merchant_risk.csv",
        "chargebacks": "chargebacks_clean.csv",
        "rings": "fraud_rings.csv",
        "members": "ring_members.csv",
        "daily": "daily_metrics.csv",
        "kyc": "kyc_master.csv",
        "summary": "summary.csv"
    }
    return {k: pd.read_csv(DATA / v) for k, v in files.items()}

d = load_data()
tx = d["tx"]
users = d["users"]
merchants = d["merchants"]
chargebacks = d["chargebacks"]
rings = d["rings"]
daily = d["daily"]
summary = d["summary"]

for frame in [tx, users, merchants, chargebacks, rings, daily]:
    for col in frame.columns:
        if frame[col].dtype == "object":
            frame[col] = frame[col].fillna("UNKNOWN")

st.title("🛡️ FraudLens AI")
st.caption("UPI Fraud Ring Detection & Merchant Risk Intelligence")

pages = ["Executive Overview", "Transactions", "Merchant Intelligence", "User & KYC Risk", "Chargebacks", "Fraud Rings", "AI Investigator"]
page = st.sidebar.radio("Navigate", pages)

st.sidebar.markdown("### Filters")
if "merchant_category_clean" in tx.columns:
    cats = sorted(tx["merchant_category_clean"].dropna().astype(str).unique())
    selected_cats = st.sidebar.multiselect("Merchant category", cats, default=cats)
else:
    selected_cats = []

if "transaction_risk_level" in tx.columns:
    levels = ["LOW", "MEDIUM", "HIGH", "CRITICAL"]
    selected_levels = st.sidebar.multiselect("Transaction risk", levels, default=levels)
else:
    selected_levels = []

filtered_tx = tx.copy()
if selected_cats:
    filtered_tx = filtered_tx[filtered_tx["merchant_category_clean"].astype(str).isin(selected_cats)]
if selected_levels:
    filtered_tx = filtered_tx[filtered_tx["transaction_risk_level"].astype(str).isin(selected_levels)]


def money(x):
    return f"₹{x/1e7:.2f} Cr" if abs(x) >= 1e7 else f"₹{x/1e5:.2f} L"


def pct(x):
    return f"{x*100:.2f}%"

if page == "Executive Overview":
    total_tx = filtered_tx["txn_id_clean"].nunique()
    total_amount = filtered_tx["amount_clean"].sum()
    cb_count = filtered_tx["chargeback_count"].sum()
    disputed = filtered_tx["disputed_amount"].sum()
    high_tx = filtered_tx["transaction_risk_level"].isin(["HIGH", "CRITICAL"]).sum()
    failed = (filtered_tx["status_clean"] == "FAILED").mean()

    a,b,c,e,f,g = st.columns(6)
    a.metric("Transactions", f"{total_tx:,}")
    b.metric("Transaction Value", money(total_amount))
    c.metric("Chargebacks", f"{int(cb_count):,}")
    e.metric("Disputed Amount", money(disputed))
    f.metric("High/Critical Txns", f"{int(high_tx):,}")
    g.metric("Failed Rate", pct(failed))

    left, right = st.columns(2)
    with left:
        chart = filtered_tx.copy()
        chart["date"] = pd.to_datetime(chart["timestamp_clean"]).dt.date
        trend = chart.groupby("date", as_index=False)["amount_clean"].sum()
        st.plotly_chart(px.line(trend, x="date", y="amount_clean", title="Transaction Value Trend"), use_container_width=True)
    with right:
        risk = filtered_tx["transaction_risk_level"].value_counts().reindex(["LOW","MEDIUM","HIGH","CRITICAL"], fill_value=0).reset_index()
        risk.columns = ["risk_level", "count"]
        st.plotly_chart(px.bar(risk, x="risk_level", y="count", title="Transaction Risk Distribution"), use_container_width=True)

    st.subheader("Top Risk Signals")
    st.dataframe(users.sort_values("risk_score", ascending=False)[[c for c in ["user_id_core","risk_score","risk_level","chargeback_ratio","failed_rate","risk_reasons"] if c in users.columns]].head(10), use_container_width=True)

elif page == "Transactions":
    st.header("Transaction Intelligence")
    st.write(f"Showing {len(filtered_tx):,} transactions after filters.")
    cols = [c for c in ["txn_id_clean","timestamp_clean","user_id_core","merchant_id_core","amount_clean","status_clean","chargeback_count","disputed_amount","transaction_risk_score","transaction_risk_level"] if c in filtered_tx.columns]
    st.dataframe(filtered_tx[cols].sort_values("transaction_risk_score", ascending=False).head(500), use_container_width=True)

    trend = filtered_tx.copy()
    trend["date"] = pd.to_datetime(trend["timestamp_clean"]).dt.date
    daily_tx = trend.groupby("date", as_index=False).agg(transaction_count=("txn_id_clean","nunique"), transaction_amount=("amount_clean","sum"), failed_count=("status_clean", lambda x: (x=="FAILED").sum()))
    st.plotly_chart(px.line(daily_tx, x="date", y="transaction_count", title="Daily Transaction Volume"), use_container_width=True)
    st.plotly_chart(px.line(daily_tx, x="date", y="failed_count", title="Daily Failed Transactions"), use_container_width=True)

elif page == "Merchant Intelligence":
    st.header("Merchant Risk Intelligence")
    top = merchants.sort_values("risk_score", ascending=False).copy()
    cols = [c for c in ["merchant_id_core","merchant_name","merchant_category_clean","transaction_count","total_amount","chargeback_count","chargeback_ratio","failed_rate","risk_score","risk_level","risk_reasons"] if c in top.columns]
    st.dataframe(top[cols].head(50), use_container_width=True)
    st.plotly_chart(px.bar(top.head(15), x="merchant_name" if "merchant_name" in top.columns else "merchant_id_core", y="risk_score", title="Top Merchant Risk Scores"), use_container_width=True)
    cat = merchants.groupby("merchant_category_clean", dropna=False).agg(transaction_count=("transaction_count","sum"), disputed_amount=("disputed_amount","sum"), chargeback_count=("chargeback_count","sum")).reset_index().sort_values("disputed_amount", ascending=False)
    st.plotly_chart(px.bar(cat, x="merchant_category_clean", y="disputed_amount", title="Disputed Amount by Merchant Category"), use_container_width=True)

elif page == "User & KYC Risk":
    st.header("User & KYC Risk")
    risk_cols = [c for c in ["user_id_core","transaction_count","total_amount","chargeback_count","disputed_amount","chargeback_ratio","failed_rate","identity_conflict_score","kyc_status_clean","risk_segment_clean","risk_score","risk_level","risk_reasons"] if c in users.columns]
    st.dataframe(users.sort_values("risk_score", ascending=False)[risk_cols].head(100), use_container_width=True)
    if "kyc_status_clean" in users.columns:
        kyc_dist = users["kyc_status_clean"].value_counts().reset_index()
        kyc_dist.columns = ["status", "count"]
        st.plotly_chart(px.pie(kyc_dist, names="status", values="count", title="KYC Status Distribution"), use_container_width=True)

elif page == "Chargebacks":
    st.header("Chargeback Intelligence")
    cb_amount = chargebacks["disputed_amount_calc"].sum() if "disputed_amount_calc" in chargebacks.columns else chargebacks.get("disputed_amount_clean", pd.Series(dtype=float)).sum()
    a,b,c = st.columns(3)
    a.metric("Chargeback Records", f"{len(chargebacks):,}")
    b.metric("Disputed Amount", money(cb_amount))
    c.metric("Delayed > 7 Days", f"{int(chargebacks.get('delayed_dispute_7d_flag', pd.Series(dtype=int)).sum()):,}")
    if "reason_code_clean" in chargebacks.columns:
        reason = chargebacks["reason_code_clean"].value_counts().reset_index()
        reason.columns = ["reason", "count"]
        st.plotly_chart(px.bar(reason, x="reason", y="count", title="Chargeback Reason Distribution"), use_container_width=True)
    st.dataframe(chargebacks.head(500), use_container_width=True)

elif page == "Fraud Rings":
    st.header("Suspicious Fraud Rings")
    st.caption("A ring is treated as suspicious connected activity supported by risk and/or dispute evidence; it is not a proof of criminal conduct.")
    if len(rings):
        st.dataframe(rings.sort_values("risk_score", ascending=False).head(100), use_container_width=True)
        selected = st.selectbox("Inspect ring", rings["ring_id"].astype(str).tolist())
        ring = rings[rings["ring_id"].astype(str) == selected].iloc[0]
        members = d["members"][d["members"]["ring_id"].astype(str) == selected]
        a,b,c,d1 = st.columns(4)
        a.metric("Risk Score", f"{ring['risk_score']:.1f}")
        b.metric("Users", int(ring["user_count"]))
        c.metric("Merchants", int(ring["merchant_count"]))
        d1.metric("Chargebacks", int(ring["chargeback_count"]))
        st.write("**Evidence:**", ring.get("risk_reasons", ""))
        st.dataframe(members, use_container_width=True)
    else:
        st.info("No suspicious rings were produced by the current graph criteria.")

elif page == "AI Investigator":
    st.header("🤖 AI Investigator")
    st.caption("Grounded investigator: answers are generated from the exported FraudLens analytics tables.")
    query = st.text_input("Ask an investigation question", placeholder="Which merchant has the highest chargeback ratio?")
    q = query.lower().strip()
    if q:
        if "highest chargeback ratio" in q or ("merchant" in q and "chargeback ratio" in q):
            row = merchants.sort_values("chargeback_ratio", ascending=False).iloc[0]
            st.success(f"Top merchant by chargeback ratio: {row.get('merchant_name', row['merchant_id_core'])} with {row['chargeback_ratio']*100:.2f}%.")
            st.dataframe(pd.DataFrame([row]))
        elif "highest disputed" in q and "merchant" in q:
            row = merchants.sort_values("disputed_amount", ascending=False).iloc[0]
            st.success(f"Merchant with highest disputed amount: {row.get('merchant_name', row['merchant_id_core'])} with {money(row['disputed_amount'])}.")
            st.dataframe(pd.DataFrame([row]))
        elif "highest disputed" in q and "user" in q:
            row = users.sort_values("disputed_amount", ascending=False).iloc[0]
            st.success(f"User with highest disputed amount: {row['user_id_core']} with {money(row['disputed_amount'])}.")
            st.dataframe(pd.DataFrame([row]))
        elif "daily" in q and "volume" in q:
            st.plotly_chart(px.line(daily, x="date", y="transaction_count", title="Daily Transaction Volume"), use_container_width=True)
        elif "reason" in q and "chargeback" in q:
            reason = chargebacks["reason_code_clean"].value_counts().reset_index()
            reason.columns = ["reason", "count"]
            st.dataframe(reason, use_container_width=True)
        elif "ring" in q:
            st.dataframe(rings.sort_values("risk_score", ascending=False).head(20), use_container_width=True)
        elif "high risk" in q and "user" in q:
            st.dataframe(users[users["risk_level"].isin(["HIGH","CRITICAL"])].sort_values("risk_score", ascending=False).head(50), use_container_width=True)
        else:
            st.info("Try: highest chargeback ratio merchant, highest disputed merchant, highest disputed user, daily transaction volume, chargeback reasons, suspicious rings, or high risk users.")

st.sidebar.caption("FraudLens AI • Datathon decision-support prototype")
'''
app_path = PROJECT_DIR / "app.py"
app_path.write_text(app_code, encoding="utf-8")
print("Streamlit app created:", app_path)

Streamlit app created: /home/oai/Documents/datathon/app.py

## 21. Create Streamlit requirements

## 21. Create Streamlit requirements

In [218]:
requirements_text = "streamlit\npandas\nnumpy\nplotly\nnetworkx\n"
requirements_path = PROJECT_DIR / "requirements.txt"
requirements_path.write_text(requirements_text, encoding="utf-8")
print("Requirements created:", requirements_path)

Requirements created: /home/oai/Documents/datathon/requirements.txt

## 22. Final project check

In [219]:
required_outputs = [
    "analytics_transactions.csv", "chargebacks_clean.csv", "kyc_master.csv",
    "merchant_master.csv", "user_risk.csv", "merchant_risk.csv",
    "fraud_rings.csv", "ring_members.csv", "daily_metrics.csv", "summary.csv"
]
check = pd.DataFrame({
    "file": required_outputs,
    "exists": [(OUTPUT_DIR / f).exists() for f in required_outputs]
})
display(check)
print("App exists:", (PROJECT_DIR / "app.py").exists())
print("Requirements exist:", (PROJECT_DIR / "requirements.txt").exists())

                         file  exists
0  analytics_transactions.csv    True
1       chargebacks_clean.csv    True
2              kyc_master.csv    True
3         merchant_master.csv    True
4               user_risk.csv    True
5           merchant_risk.csv    True
6             fraud_rings.csv    True
7            ring_members.csv    True
8           daily_metrics.csv    True
9                 summary.csv    True

App exists: True
Requirements exist: True